Repository pmd/pmd, pull requests merged in 2018-06, with the labels that each got.

#1183 [java] fixed typos in rule remediation
  docs/pages/pmd/rules/java/performance.md
  pmd-java/src/main/resources/category/java/performance.xml
Labels: in:documentation

#1155 [java] AtLeastOneConstructor supports Lombok
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateMethodRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/AtLeastOneConstructorRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryConstructorRule.java
  pmd-java/src/main/resources/category/java/codestyle.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/AtLeastOneConstructor.xml
Labels: a:false-negative, a:false-positive, is:waiting-for-review

#1203 [java] Prop up Ncss report levels, allow greater configurability
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/NcssCountRule.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/NcssCount.xml
Labels: is:low-impact

#1206 [java] Recommend StringBuilder next to StringBuffer
  pmd-java/src/main/resources/category/java/performance.xml
Labels: in:documentation

#1213 [java] CommentDefaultAccessModifier false positive with nested interf…
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/CommentDefaultAccessModifierRule.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/CommentDefaultAccessModifier.xml
Labels: a:false-positive
