Repository pmd/pmd, pull requests merged in 2018-08, with the labels that each got.

#1281 Test Framework: Only show "Unit Tests" node, if there are unit tests
  pmd-test/src/main/java/net/sourceforge/pmd/testframework/PMDTestRunner.java
Labels: in:pmd-internals, is:low-impact

#1269 [core] Test Framework: Sort violations by line/column
  docs/pages/release_notes.md
  pmd-core/src/test/java/net/sourceforge/pmd/ReportTest.java
  pmd-test/src/main/java/net/sourceforge/pmd/testframework/RuleTst.java
  pmd-test/src/test/java/net/sourceforge/pmd/testframework/RuleTstTest.java
Labels: in:pmd-internals

#1275 [jsp] Issue #1274 - Support EL in tag attributes
  pmd-jsp/etc/grammar/JspParser.jjt
  pmd-jsp/src/test/java/net/sourceforge/pmd/lang/jsp/JspParserTest.java
Labels: a:bug

#1295 [java] Small improvements to Java qualified names
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/JavaTypeQualifiedName.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/QualifiedNameFactory.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/QualifiedNameResolver.java
Labels: is:low-impact

#1301 [core] PMD stops processing file completely, if one rule in a rule ch…
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRuleChainVisitor.java
  pmd-core/src/test/java/net/sourceforge/pmd/RuleSetTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/metrics/xpath/XPathMetricFunctionTest.java
Labels: a:bug

#1299 [java] RedundantFieldInitializer - NumberFormatException with Long
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTLiteral.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/RedundantFieldInitializer.xml
Labels: a:bug

#1305 [core] Deprecate ReportTree
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/report/AbstractReportNode.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/report/ClassNode.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/report/PackageNode.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/report/ReportHTMLPrintVisitor.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/report/ReportTree.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/report/ReportVisitor.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/report/ViolationNode.java
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/YAHTMLRenderer.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/AbstractRendererTst.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/YAHTMLRendererTest.java
  pmd-core/src/test/resources/net/sourceforge/pmd/renderers/yahtml/YAHTMLSampleClass1.html
  pmd-core/src/test/resources/net/sourceforge/pmd/renderers/yahtml/YAHTMLSampleClass2.html
  pmd-core/src/test/resources/net/sourceforge/pmd/renderers/yahtml/index.html
Labels: an:enhancement, in:pmd-internals
