Repository pmd/pmd, pull requests merged in 2018-02, with the labels that each got.

#914 [doc] Apex @SuppressWarnings documentation updated
  docs/pages/pmd/userdocs/suppressing_warnings.md
Labels: in:documentation

#916 [java] Add ghost production for type annotations to cleanup the grammar
  pmd-java/etc/grammar/Java.jjt
Labels: an:enhancement

#920 [java] Update valid identifiers in grammar
  pmd-java/etc/grammar/Java.jjt
Labels: an:enhancement, in:pmd-internals

#923 [ci] Use Java9 for building PMD
  .travis.yml
  .travis/build-coveralls.sh
  .travis/build-deploy.sh
  .travis/build-sonar.sh
  docs/pages/release_notes.md
  pmd-apex-jorje/pom.xml
  pmd-apex/pom.xml
  pmd-doc/pom.xml
  pmd-java8/pom.xml
  pom.xml
Labels: in:pmd-internals

#924 [java] ConsecutiveLiteralAppends with types other than string
  docs/pages/release_notes.md
  pmd-java/src/main/resources/category/java/performance.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/ConsecutiveLiteralAppends.xml
Labels: a:bug, in:documentation

#918 [doc] Add qa-eclipse as new tool
  docs/pages/pmd/userdocs/tools/tools.md
Labels: in:documentation

#927 [java][doc] Fix example of AbstractClassWithoutAnyMethod
  pmd-java/src/main/resources/category/java/design.xml
Labels: a:bug, in:documentation

#801 [ui] Rule property edition + new settings persistence logic for the designer
  pmd-core/src/main/java/net/sourceforge/pmd/rules/RuleBuilder.java
  pmd-ui/pom.xml
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/Designer.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/EditPropertyDialogController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/EventLogController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/ExportXPathWizardController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/MainDesignerController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/NodeInfoPanelController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/SourceEditorController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/XPathPanelController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/model/ASTManager.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/model/ObservableRuleBuilder.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/model/ObservableXPathRuleBuilder.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/model/XPathEvaluator.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/DesignerUtil.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/PropertyDescriptorSpec.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/beans/BeanModelNode.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/beans/BeanModelNodeSeq.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/beans/BeanNodeVisitor.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/beans/RestorePropertyVisitor.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/beans/SettingsOwner.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/beans/SettingsPersistenceUtil.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/beans/SimpleBeanModelNode.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/beans/XmlInterface.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/beans/XmlInterfaceVersion1.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/beans/converters/LanguageVersionConverter.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/beans/converters/PropertyTypeIdConverter.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/beans/converters/RulePriorityConverter.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/codearea/AvailableSyntaxHighlighters.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/codearea/CustomCodeArea.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/codearea/StyleLayer.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/codearea/syntaxhighlighting/XPathSyntaxHighlighter.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/controls/PropertyTableView.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/controls/ScopeHierarchyTreeCell.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/controls/ScopeHierarchyTreeItem.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/settings/AppSetting.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/settings/SettingsOwner.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/settings/XMLSettingsLoader.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/settings/XMLSettingsSaver.java
  pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/css/designer.css
  pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/fxml/designer.fxml
  pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/fxml/edit-property-dialog.fxml
  pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/fxml/editor.fxml
  pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/fxml/event-log.fxml
  pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/fxml/node-info.fxml
  pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/fxml/xpath.fxml
  pmd-ui/src/test/java/net/sourceforge/pmd/util/fxdesigner/util/DesignerUtilTest.java
Labels: an:enhancement, in:ui

#937 Use Files.move instead of File.renameTo
  pmd-core/src/main/java/net/sourceforge/pmd/document/DocumentFile.java
Labels: a:bug

#930 [ecmascript] Update rhino to 1.7.7.2
  docs/pages/release_notes.md
  pom.xml
Labels: an:enhancement
