Repository pmd/pmd, pull requests merged in 2018-04, with the labels that each got.

#1013 [ui] Add Generate XPath from stack trace context menu
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/XPathPanelController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/DesignerUtil.java
  pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/fxml/generate-xpath-from-stack-trace.fxml
Labels: in:ui

#1029 [java] False positive for useless parenthesis
  docs/pages/release_notes.md
  pmd-java/src/main/resources/category/java/codestyle.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UselessParentheses.xml
Labels: a:false-positive

#1041 [java] Make BasicProjectMemoizer thread safe.
  pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/BasicProjectMemoizer.java
Labels: a:bug, in:metrics
