Repository pmd/pmd, pull requests merged in 2018-05, with the labels that each got.

#1083 [java] Fix lambda qname in enum constants
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/QualifiedNameResolver.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/JavaQualifiedNameTest.java
Labels: is:waiting-for-review

#1144 [core] Update issue template
  .github/ISSUE_TEMPLATE.md
Labels: is:low-impact

#1147 [core] Fix JCommander help for -min option
  pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDParameters.java
Labels: is:low-impact

#1149 [java] Fix doc for CommentDefaultAccessModifierRule
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/CommentDefaultAccessModifierRule.java
  pmd-java/src/main/resources/category/java/codestyle.xml
Labels: a:bug, in:documentation

#1135 Update to ci scripts
  .travis.yml
  .travis/build-coveralls.sh
  .travis/build-deploy.sh
  .travis/build-doc.sh
  .travis/build-sonar.sh
  .travis/logger.sh
  .travis/release.sh
  pom.xml
Labels: is:waiting-for-review

#1156 [ci] Use latest pmd on self
  pom.xml
Labels: is:waiting-for-review

#1161 [java] Fix IdenticalCatchBranches false positive
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/IdenticalCatchBranchesRule.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/IdenticalCatchBranches.xml
Labels: is:waiting-for-review
