Repository pmd/pmd, pull requests merged in 2018-11, with the labels that each got.

#1424 [doc] #1341 Updating Regex Values in default Value Property
  pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleDocGenerator.java
  pmd-doc/src/test/resources/expected/sample.md
  pmd-doc/src/test/resources/rulesets/ruledoctest/sample.xml
Labels: in:documentation

#1430 [doc] Who really knows regex?
  docs/pages/pmd/userdocs/suppressing_warnings.md
Labels: in:documentation

#1431 [ui] Remove old GUI applications (designerold, bgastviewer)
  docs/pages/7_0_0_release_notes.md
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/util/designer/CodeEditorTextPane.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/designer/CreateXMLRulePanel.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/designer/DFAPanel.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/designer/Designer.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/designer/LineGetter.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/Viewer.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/ASTPanel.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/ActionCommands.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/EvaluationResultsPanel.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/MainFrame.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/ParseExceptionHandler.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/SourceCodePanel.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/XPathPanel.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/menu/ASTNodePopupMenu.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/menu/AttributesSubMenu.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/menu/SimpleNodeSubMenu.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/gui/menu/XPathFragmentAddingItem.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/model/ASTModel.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/model/AttributeToolkit.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/model/SimpleNodeTreeNodeAdapter.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/model/ViewerModel.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/model/ViewerModelEvent.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/model/ViewerModelListener.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/viewer/util/NLS.java
  pmd-core/src/test/java/net/sourceforge/pmd/util/designer/DesignerTest.java
  pmd-dist/src/main/assembly/bin.xml
  pmd-dist/src/main/scripts/bgastviewer.bat
  pmd-dist/src/main/scripts/designerold.bat
  pmd-dist/src/main/scripts/run.sh
Labels: in:ui

#1449 [ui] make the language dependencies optional
  pmd-ui/pom.xml
Labels: a:suggestion, an:enhancement

#1448 [docs] Update "Testing your rules"
  docs/Gemfile.lock
  docs/pages/pmd/userdocs/extending/testing.md
Labels: in:documentation

#1423 [doc] Add pmd 7.0.0 dev page to docs
  docs/_data/sidebars/pmd_sidebar.yml
  docs/pages/next_major_development.md
  docs/pages/release_notes.md
  docs/pages/release_notes_old.md
Labels: in:documentation

#1467 [java] Fix broken link in CyclomaticComplexity
  pmd-java/src/main/resources/category/java/design.xml
Labels: a:bug, in:documentation, is:low-impact

#1469 [core] Configurable max loops in DAAPathFinder
  pmd-core/src/main/java/net/sourceforge/pmd/lang/dfa/pathfinder/DAAPathFinder.java
Labels: in:data-flow

#1472 [core] XMLRenderer: ProcessingErrors from exceptions without a messag…
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/Report.java
  pmd-core/src/test/java/net/sourceforge/pmd/RuleSetTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/AbstractRendererTst.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/PapariTextRendererTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/TextRendererTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/XMLRendererTest.java
Labels: a:bug
