Repository pmd/pmd, pull requests merged in 2018-12, with the labels that each got.

#1494 [java] 1151: Rephrase ImmutableField documentation in design.xml
  pmd-java/src/main/resources/category/java/design.xml
Labels: in:documentation

#1457 [java] Adding test for Issue #647
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/JUnitTestsShouldIncludeAssert.xml
Labels: is:WIP

#1522 [plsql] Parse Exception when using SELECT COUNT(*)
  docs/pages/release_notes.md
  pmd-plsql/etc/grammar/PldocAST.jjt
  pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/SelectExpressionsTest.java
  pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/SelectCount.pls
  pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/SelectExpressions.pls
Labels: a:bug

#1524 [plsql] Parse Exception with OUTER/INNER Joins
  docs/pages/release_notes.md
  pmd-plsql/etc/grammar/PldocAST.jjt
  pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/JoinClauseTest.java
  pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/FullOuterJoin.pls
  pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/InnerJoinSubquery.pls
  pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/InnerNaturalJoin.pls
Labels: a:bug

#1525 [plsql] Parse Exception with IS NOT NULL
  docs/pages/release_notes.md
  pmd-plsql/etc/grammar/PldocAST.jjt
  pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/IsNull.pls
Labels: a:bug

#1520 [java] New rule: ForLoopVariableCount: check the number of control variables in a for loop
  pmd-java/src/main/resources/category/java/codestyle.xml
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/ForLoopVariableCountTest.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/ForLoopVariableCount.xml
Labels: a:new-rule

#1542 [apex] Include the documentation category
  pmd-apex/src/main/resources/category/apex/categories.properties
Labels: a:bug, in:documentation
