Repository pmd/pmd, pull requests merged in 2018-07, with the labels that each got.

#1219 [java] Fix cyclo miscounting ternaries
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAssertStatement.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTConditionalExpression.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTForStatement.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/CycloMetric.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/visitors/CycloBaseVisitor.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/visitors/CycloPathAwareDecorator.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/metrics/impl/xml/CycloTest.xml
Labels: a:bug, in:metrics

#1220 [java] Fix unnecessaryFQCN false positive with import-on-demand
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTImportDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryFullyQualifiedName.xml
Labels: a:false-positive

#1231 [doc] Minor typo fix in installation.md
  docs/pages/pmd/userdocs/installation.md
Labels: in:documentation

#1229 [java] Fix tests of ClassTypeResolver
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java
  pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverTest.java
Labels: in:ast, in:type-resolution

#1262 [java] NPath complexity false negative due to overflow
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/impl/visitors/NpathBaseVisitor.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/NPathComplexityRule.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/metrics/impl/xml/NPathTest.xml
Labels: a:false-negative

#1264 [cpp] Fix NullPointerException in CPPTokenizer:99
  pmd-cpp/src/main/java/net/sourceforge/pmd/cpd/CPPLanguage.java
Labels: a:bug
