Repository pmd/pmd, pull requests merged in 2018-10, with the labels that each got.

#1368 [doc] Updated outdated note in the building documentation.
  BUILDING.md
Labels: in:documentation

#1370 [java] PMD crashes with java.lang.ClassFormatError: Absent Code
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/JavaTypeQualifiedName.java
Labels: a:bug

#1392 [java] Fix the rulechain usage
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/security/HardCodedCryptoKeyRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/security/InsecureCryptoIvRule.java
Labels: an:enhancement, for:performance

#1406 [jsp] Fix issue 1402: JspTokenManager has a problem about jsp scriptlet
  pmd-jsp/etc/grammar/JspParser.jjt
Labels: a:bug

#1414 [doc] Fix broken link. Fixes #1412
  docs/pages/pmd/userdocs/cpd.md
Labels: in:documentation

#1399 [doc] Use https://pmd.sourceforge.io/ruleset_2_0_0.xsd as schema location
  docs/pages/pmd/userdocs/extending/writing_pmd_rules.md
  docs/pages/pmd/userdocs/extending/writing_xpath_rules.md
  docs/pages/pmd/userdocs/making_rulesets.md
Labels: in:documentation

#1361 [doc] Update cpd.md with information about risks
  docs/pages/pmd/userdocs/cpd.md
Labels: in:documentation

#1410 [java] UnusedImports false positive for static import with package-pr…
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/ImportWrapper.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/unusedimports/PackagePrivateUtils.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/unusedimports/PublicUtils.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedImports.xml
Labels: a:false-positive

#1409 [java] UnusedImports false positive with static ondemand import with …
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedImportsRule.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/unusedimports/ClassWithStringConstants.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedImports.xml
Labels: a:false-positive
