Repository pmd/pmd, pull requests merged in 2018-03, with the labels that each got.

#948 [java] Migrate internal rulesets used in unit tests
  pmd-java/src/test/java/net/sourceforge/pmd/RuleSetFactoryTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/cli/CLITest.java
  pmd-java/src/test/resources/net/sourceforge/pmd/ant/xml/pmdtasktest.xml
Labels: in:pmd-internals

#950 [java] Avoid a NPE in Type Resolution
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinition.java
Labels: a:bug, in:type-resolution

#951 [java] Add ignoredAnnotations property to unusedPrivateMethod rule
  docs/pages/pmd/rules/java/bestpractices.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateMethodRule.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml
Labels: an:enhancement

#952 [java] SignatureDeclareThrowsException's IgnoreJUnitCompletely property not honored for constructors
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/SignatureDeclareThrowsExceptionRule.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/SignatureDeclareThrowsException.xml
Labels: a:bug

#1011 [ui] Improvements to designer syntax highlighting
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/codearea/SimpleRegexSyntaxHighlighter.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/codearea/syntaxhighlighting/ApexSyntaxHighlighter.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/codearea/syntaxhighlighting/HighlightClasses.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/codearea/syntaxhighlighting/JavaSyntaxHighlighter.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/codearea/syntaxhighlighting/XPathSyntaxHighlighter.java
  pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/css/editor-theme.css
Labels: in:ui
