Repository pmd/pmd, pull requests merged in 2019-05, with the labels that each got.

#1816 [apex] Fix ApexDoc handling with inner classes
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexTreeBuilder.java
  pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/documentation/xml/ApexDoc.xml
Labels: a:bug

#1823 refactor: Make the children array never null
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/AbstractApexNodeBase.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/Node.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AbstractJavaNode.java
  pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/AbstractEcmascriptNode.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/AbstractJspNode.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/AbstractPLSQLNode.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/AbstractVFNode.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/AbstractVmNode.java
Labels: in:pmd-internals

#1827 [core] Add checker-qual dependency
  pmd-core/pom.xml
Labels: in:pmd-internals

#1837 [core] Minor performance improvements
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/GUI.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/designer/Designer.java
Labels: for:performance, is:low-impact

#1840 [java] Whitelist serialPersistentFields
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/FieldNamingConventionsRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/documentation/CommentRequiredRule.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/FieldNamingConventions.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/documentation/xml/CommentRequired.xml
Labels: a:false-positive

#1798 [java] Make CommentDefaultAccessModifier work for top-level classes
  docs/pages/pmd/rules/java.md
  docs/pages/pmd/rules/java/codestyle.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/CommentDefaultAccessModifierRule.java
  pmd-java/src/main/resources/category/java/codestyle.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/CommentDefaultAccessModifier.xml
Labels: a:false-negative

#1843 [java] Fix annotated module declaration
  pmd-java/etc/grammar/Java.jjt
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/JDKVersionTest.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/jdk9_module_info_with_annot.java
Labels: in:ast
