Repository pmd/pmd, pull requests merged in 2019-06, with the labels that each got.

#1844 [plsql] Parentheses stopped working
  docs/pages/release_notes.md
  pmd-plsql/etc/grammar/PldocAST.jjt
  pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/WhereClauseTest.java
  pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/WhereClauseParens.pls
Labels: a:bug

#1866 [docs] Clarify violationSuppressXPath docs
  docs/pages/pmd/userdocs/suppressing_warnings.md
Labels: in:documentation

#1855 [java] Make new java expression grammar stricter
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAmbiguousName.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTArrayAccess.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTArrayAllocation.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTArrayAllocationDims.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTArrayDimExpr.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAssignmentExpression.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTCharLiteral.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTClassLiteral.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTConstructorCall.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTFieldAccess.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTIntersectionType.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTLambdaParameter.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTLambdaParameterList.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTMethodCall.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTParenthesizedExpression.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTStringLiteral.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTSuperExpression.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTThisExpression.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTType.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableInitializer.java
Labels: an:enhancement, in:ast

#1871 (doc) Improve documentation for ant task
  docs/pages/pmd/userdocs/tools/ant.md
Labels: in:documentation
