Repository pmd/pmd, pull requests merged in 2019-04, with the labels that each got.

#1770 [java] JUnitTestContainsTooManyAsserts uses XPath 2
  pmd-java/src/main/resources/category/java/bestpractices.xml
Labels: for:performance

#1773 [core] Declare fn namespace on Saxon
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQuery.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/XPathRuleTest.java
Labels: an:enhancement, in:xpath

#1767 [java] Fixes to JavaTypeDefinitionSimple
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/JavaTypeDefinitionSimple.java
Labels: a:bug

#1797 [core] Module pmd-lang-test is missing javadoc artifact
  docs/pages/release_notes.md
  pmd-lang-test/pom.xml
  pmd-lang-test/src/main/java/net/sourceforge/pmd/lang/ast/test/PlaceHolder.java
  pmd-lang-test/src/main/java/net/sourceforge/pmd/lang/ast/test/package-info.java
  pom.xml
Labels: in:pmd-internals

#1795 [core] Ruleset Compatibility fails with excluding rules
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactoryCompatibility.java
  pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryCompatibilityTest.java
  pmd-core/src/test/resources/rulesets/dummy/oldbasic.xml
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/PMD5RulesetTest.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/pmd5ruleset.xml
Labels: a:bug
