Repository pmd/pmd, pull requests merged in 2019-10, with the labels that each got.

#2032 [core] Allow adding SourceCode directly into CPD
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPD.java
Labels: an:enhancement, in:cpd

#2066 [java] Deprecate AbstractJavaRule#getDeclaringType(Node)
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJavaRule.java
Labels: is:deprecation

#2083 [core] Enable type resolution by default for XPath rules
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/XPathRule.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/XPathRuleTest.java
Labels: an:enhancement

#2084 [core] Deprecate Parser#getSuppressMap
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/lang/Parser.java
Labels: is:deprecation
