Repository pmd/pmd, pull requests merged in 2019-01, with the labels that each got.

#1557 [java] Fix default methods should not be abstract
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTMethodDeclaration.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ASTMethodDeclarationTest.java
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTMethodDeclarationTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/KotlinTestingDsl.kt
  pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/TestUtils.kt
Labels: a:bug, is:waiting-for-review

#1561 [doc] Add note which rules replace the deprecated rule.
  docs/pages/next_major_development.md
  pmd-java/src/main/resources/category/java/codestyle.xml
  pmd-java/src/main/resources/category/java/design.xml
Labels: in:documentation, is:low-impact

#1567 [java] Share utilities defined in ClassTypeResolverTest
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ParserTstUtil.java
  pmd-java/src/test/java/net/sourceforge/pmd/typeresolution/ClassTypeResolverTest.java
Labels: is:low-impact

#1577 [ui] Improve XPath autocompletion
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/XPathPanelController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/model/XPathSuggestions.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/autocomplete/AstPackageExplorer.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/autocomplete/CompletionResult.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/autocomplete/CompletionResultSource.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/autocomplete/NodeNameFinder.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/autocomplete/ResultSelectionStrategy.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/autocomplete/XPathAutocompleteProvider.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/autocomplete/XPathCompletionSource.java
  pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/less/designer.less
Labels: in:ui

#1550 [core] Deprecate StatisticalRule
  docs/pages/release_notes.md
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/AbstractStatisticalApexRule.java
  pmd-core/src/main/java/net/sourceforge/pmd/Report.java
  pmd-core/src/main/java/net/sourceforge/pmd/ThreadSafeReportListener.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/stat/StatisticalRule.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/stat/StatisticalRuleHelper.java
  pmd-core/src/main/java/net/sourceforge/pmd/stat/DataPoint.java
  pmd-core/src/main/java/net/sourceforge/pmd/stat/Metric.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractStatisticalJavaRule.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/AbstractStatisticalPLSQLRule.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/rule/AbstractStatisticalVmRule.java
Labels: is:deprecation

#1576 [ui] Clear designer toolbar
  pmd-ui/pom.xml
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/EventLogController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/MainDesignerController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/NodeInfoPanelController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/SourceEditorController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/XPathPanelController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/model/ObservableXPathRuleBuilder.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/popups/EditPropertyDialogController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/AbstractController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/DesignerUtil.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/beans/RestorePropertyVisitor.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/beans/SettingsOwner.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/controls/ToolbarTitledPane.java
  pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/fxml/auxclasspath-setup-popup.fxml
  pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/fxml/designer.fxml
  pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/fxml/editor.fxml
  pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/fxml/xpath.fxml
  pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/less/constants.less
  pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/less/designer.less
Labels: in:ui

#1580 [ui] Fix package exploration in jars
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/XPathPanelController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/autocomplete/AstPackageExplorer.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/autocomplete/XPathAutocompleteProvider.java
Labels: a:bug, in:ui

#1582 [ui] Reduce event log noise in designer
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/EventLogController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/XPathPanelController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/model/ASTManager.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/model/LogEntry.java
Labels: in:ui, is:low-impact

#1584 [core] Fixes 1196: inconsistencies of clones returned by different CPD executions for the same files
  pmd-core/src/main/java/net/sourceforge/pmd/util/FileFinder.java
Labels: in:cpd

#1585 [ui] Convert event log into a popup
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/Designer.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/EventLogController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/MainDesignerController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/NodeInfoPanelController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/SourceEditorController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/model/ASTManager.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/model/EventLogger.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/model/LogEntry.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/model/ObservableRuleBuilder.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/popups/AuxclasspathSetupController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/popups/EditPropertyDialogController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/popups/EventLogController.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/DesignerUtil.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/SoftReferenceCache.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/autocomplete/XPathCompletionSource.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/codearea/NodeStyleSpan.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/codearea/SimpleRegexSyntaxHighlighter.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/controls/ASTTreeItem.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/controls/PropertyTableView.java
  pmd-ui/src/main/java/net/sourceforge/pmd/util/fxdesigner/util/controls/ToolbarTitledPane.java
  pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/fxml/designer.fxml
  pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/fxml/event-log.fxml
  pmd-ui/src/main/resources/net/sourceforge/pmd/util/fxdesigner/less/designer.less
Labels: in:ui

#1596 [plsql] Parse Exception when functions are used with LIKE
  docs/pages/release_notes.md
  pmd-plsql/etc/grammar/PldocAST.jjt
  pmd-plsql/src/main/ant/alljavacc.xml
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTCompoundCondition.java
  pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/ASTCompoundConditionTest.java
  pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/WhereClauseLike.pls
Labels: a:bug

#1594 [plsql] ParseException when using TableCollectionExpression
  docs/pages/release_notes.md
  pmd-plsql/etc/grammar/PldocAST.jjt
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/PLSQLParserVisitorAdapter.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/AbstractPLSQLRule.java
  pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/TableCollectionExpression.java
  pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/TableCollectionExpressionExamples.pls
  pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/TableCollectionExpressionIssue1526.pls
Labels: a:bug

#1450 [core] Rework pmd-dist so that it is usable for custom PMD distributions
  pmd-dist/pom.xml
  pmd-dist/src/main/resources/LICENSE
  pmd-dist/src/main/resources/assemblies/pmd-bin.xml
  pmd-dist/src/main/resources/assemblies/pmd-src.xml
  pmd-dist/src/main/resources/scripts/bgastviewer.bat
  pmd-dist/src/main/resources/scripts/cpd.bat
  pmd-dist/src/main/resources/scripts/cpdgui.bat
  pmd-dist/src/main/resources/scripts/designer.bat
  pmd-dist/src/main/resources/scripts/designerold.bat
  pmd-dist/src/main/resources/scripts/pmd.bat
  pmd-dist/src/main/resources/scripts/run.sh
  pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java
Labels: an:enhancement
