Repository pmd/pmd, pull requests merged in 2019-03, with the labels that each got.

#1711 [apex] Introduce quickstart ruleset
  pmd-apex/src/main/resources/rulesets/apex/quickstart.xml
  pmd-apex/src/main/resources/rulesets/apex/ruleset.xml
Labels: an:enhancement, has:pr

#1697 [doc] Update CPD documentation
  docs/pages/pmd/devdocs/major_contributions/adding_new_cpd_language.md
Labels: in:documentation

#1743 [java] AvoidDuplicateLiterals warning about deprecated separator property when not used
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRule.java
  pmd-core/src/test/java/net/sourceforge/pmd/AbstractRuleTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidDuplicateLiteralsTest.java
Labels: a:bug
