Repository pmd/pmd, pull requests merged in 2019-09, with the labels that each got.

#1994 [core] Resolve pmd-report failure when java folder in filepath
  pmd-core/etc/xslt/pmd-report.xslt
Labels: a:bug

#1958 [java] Compare ignored annotations by fully qualified names only
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/TypeHelper.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateFieldTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/unusedprivatefield/Value.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateField.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/BigIntegerInstantiation.xml
Labels: a:false-negative

#1825 [core] Support NoAttribute for XPath
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/AttributeAxisIterator.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/NoAttribute.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/xpath/NoAttributeTest.java
Labels: an:enhancement, in:xpath

#1959 [apex] Expose supertype name of UserClass
  docs/pages/pmd/rules/apex/bestpractices.md
  docs/pages/release_notes.md
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTUserClass.java
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTUserInterface.java
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTUserTrigger.java
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/TriggerUsage.java
  pmd-apex/src/main/resources/category/apex/bestpractices.xml
  pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ASTUserClassTest.java
  pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ASTUserInterfaceTest.java
  pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ASTUserTriggerTest.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/AttributeAxisIterator.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/saxon/AttributeNode.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQuery.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/DummyLanguageModule.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/xpath/AttributeAxisIteratorTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/DummyNodeWithListAndEnum.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/JaxenXPathRuleQueryTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQueryTest.java
Labels: an:enhancement

#2013 [java] Mark typeres implementation as internal API
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTCompilationUnit.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/ClassTypeResolver.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/MethodType.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/MethodTypeResolution.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/PMDASMClassLoader.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/TypeResolutionFacade.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typedefinition/TypeDefinition.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typeinference/Bound.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typeinference/BoundOrConstraint.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typeinference/Constraint.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typeinference/InferenceRuleType.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typeinference/TypeInferenceResolver.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/typeinference/Variable.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/typeresolution/visitors/PMDASMVisitor.java
Labels: is:deprecation

#2031 [java,apex] Deprecate CanSuppressWarnings
  docs/pages/release_notes.md
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/CanSuppressWarnings.java
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/ApexRuleViolation.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/CanSuppressWarnings.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJavaRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/JavaRuleViolation.java
Labels: is:deprecation
