Repository pmd/pmd, pull requests merged in 2020-04, with the labels that each got.

#2387 [java] Add record support to the newer symbol table
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnyTypeDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTArgumentList.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTLambdaParameterList.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTList.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTMethodDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTModifierList.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTRecordComponent.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTRecordComponentList.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTRecordConstructorDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTRecordDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTTypeArguments.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableDeclaratorId.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AbstractMethodOrConstructorDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AbstractTypedSymbolDeclarator.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/InternalApiBridge.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/InternalInterfaces.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/SideEffectingVisitorAdapter.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/SymbolDeclaratorNode.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JClassSymbol.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/impl/ArraySymbolImpl.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/impl/ImplicitMemberSymbols.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/impl/SymbolToStrings.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/impl/UnresolvedClassImpl.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/impl/ast/AstClassSym.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/impl/ast/AstSymFactory.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/impl/ast/AstSymbolMakerVisitor.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/impl/reflect/ReflectedClassImpl.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SymbolTableResolver.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/VarOnlySymTable.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/Java14PreviewTest.java
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/AstSymbolResolverTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/AstSymbolTests.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/table/internal/VarScopingTest.kt
Labels: in:symbol-table

#2372 [core] Deprecations for token managers
  pmd-core/src/main/java/net/sourceforge/pmd/lang/Parser.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/TokenManager.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractTokenManager.java
Labels: is:deprecation

#2370 [doc] Improve documentation about incremental analysis
  docs/pages/pmd/userdocs/incremental_analysis.md
  docs/pages/release_notes.md
Labels: in:documentation

#2385 [java] Make yield statements more conditional
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/Node.java
  pmd-java/etc/grammar/Java.jjt
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/Java14Test.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java14/YieldStatements.java
Labels: in:ast

#2403 [java] #2402 fix false-positives on Primitive Streams
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml
Labels: a:false-positive

#2401 [doc] Update DoNotUseThreads rule documentation
  pmd-java/src/main/resources/category/java/multithreading.xml
Labels: in:documentation

#2388 [lang-test] Use tree dumps for regression tests
  pmd-core/src/main/java/net/sourceforge/pmd/util/treeexport/TextTreeRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/treeexport/TreeRenderers.java
  pmd-lang-test/pom.xml
  pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/AstMatcherDslAdapter.kt
  pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/BaseParsingHelper.kt
  pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/BaseTreeDumpTest.kt
  pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/NodePrinters.kt
  pmd-scala/src/test/kotlin/net/sourceforge/pmd/lang/scala/ast/ScalaParserTests.kt
  pmd-scala/src/test/resources/net/sourceforge/pmd/lang/scala/ast/testdata/List.scala
  pmd-scala/src/test/resources/net/sourceforge/pmd/lang/scala/ast/testdata/List.txt
  pmd-scala/src/test/resources/net/sourceforge/pmd/lang/scala/ast/testdata/package.scala
  pmd-scala/src/test/resources/net/sourceforge/pmd/lang/scala/ast/testdata/package.txt
  pom.xml
Labels: in:ast

#2389 [java] Implement AST disambiguation
  pmd-core/src/main/java/net/sourceforge/pmd/internal/util/IteratorUtil.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/javacc/JavaccToken.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAmbiguousName.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTClassOrInterfaceType.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTFieldAccess.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableAccess.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AstDisambiguationPass.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AstImplUtil.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/InternalApiBridge.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/TokenUtils.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/JavaAstProcessor.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JClassSymbol.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JTypeDeclSymbol.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/impl/ast/AstClassSym.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/impl/reflect/ReflectedClassImpl.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/AbstractSymbolTable.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SemanticChecksLogger.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SymbolTableHelper.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SymbolTableResolver.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/TypeMemberSymTable.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/TypeOnlySymTable.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ParserCornersTest.java
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTMethodReferenceTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTSuperExpressionTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTThisExpressionTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTTypeTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/TestExtensions.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/TypeDisambiguationTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/VarDisambiguationTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/AstSymbolTests.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/ClassPathSymbolResolverTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/table/internal/LocalTypeScopesTest.kt
Labels: in:symbol-table

#2417 [core] Host own javadoc on docs.pmd-code.org
  .travis/build-doc.sh
  .travis/pmd-code-api.sh
  .travis/setup-secrets.sh
  docs/_config.yml
  docs/_plugins/javadoc_tag.rb
  docs/pages/pmd/projectdocs/committers/releasing.md
  pmd-lang-test/pom.xml
  pom.xml
Labels: in:documentation

#2404 [core] Add JsonRenderer
  docs/pages/pmd/userdocs/pmd_report_formats.md
  docs/pages/release_notes.md
  docs/report-examples/pmd-report-json.json
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/JsonRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/RendererFactory.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/JsonRendererTest.java
  pmd-core/src/test/resources/net/sourceforge/pmd/renderers/json/empty.json
  pmd-core/src/test/resources/net/sourceforge/pmd/renderers/json/expected-configurationerror.json
  pmd-core/src/test/resources/net/sourceforge/pmd/renderers/json/expected-multiple.json
  pmd-core/src/test/resources/net/sourceforge/pmd/renderers/json/expected-processingerror-no-message.json
  pmd-core/src/test/resources/net/sourceforge/pmd/renderers/json/expected-processingerror.json
  pmd-core/src/test/resources/net/sourceforge/pmd/renderers/json/expected-suppressed.json
  pmd-core/src/test/resources/net/sourceforge/pmd/renderers/json/expected.json
Labels: an:enhancement

#2452 [doc] Fix "Making Rulesets" doc sample code indentation
  docs/pages/pmd/userdocs/making_rulesets.md
Labels: in:documentation
