Repository pmd/pmd, pull requests merged in 2020-01, with the labels that each got.

#2193 [core] Fix odd logic in test runner
  pmd-test/src/main/java/net/sourceforge/pmd/testframework/PMDTestRunner.java
Labels: a:bug

#2194 [java] Fix odd logic in AvoidUsingHardCodedIPRule
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AvoidUsingHardCodedIPRule.java
Labels: a:bug

#2237 [core] Add Node#findDescendantsOfType with crossFindBoundaries that
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AbstractNode.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/Node.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/AbstractNodeTransversalTest.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/PreserveStackTraceRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/ConstructorCallsOverridableMethodRule.java
Labels: in:ast

#2256 [doc] Corrected XML attributes in release notes
  docs/pages/release_notes_old.md
Labels: in:documentation
