Repository pmd/pmd, pull requests merged in 2020-03, with the labels that each got.

#2317 [apex] New Rule - Test Methods Must Be In Test Classes
  pmd-apex/src/main/resources/category/apex/errorprone.xml
  pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/errorprone/TestMethodsMustBeInTestClassesTest.java
  pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/errorprone/xml/TestMethodsMustBeInTestClasses.xml
Labels: a:new-rule

#2326 [plsql] Added XML functions to parser: extract(xml), xml_root and fixed xml_forest
  pmd-plsql/etc/grammar/PldocAST.jjt
  pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/FunctionsTest.java
  pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/ExtractExpressions.pls
  pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/XMLFunctions.pls
Labels: an:enhancement

#2345 [java] Fix Java14 processing errors
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnyTypeBodyDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableDeclaratorId.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AbstractTypeBodyDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractInefficientZeroCheck.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractPoorMethodCall.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/MissingOverrideRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/InsufficientStringBufferDeclarationRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/StringToStringRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/VariableNameDeclaration.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/Java14PreviewTest.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/MissingOverride.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/InefficientEmptyStringCheck.xml
  pmd-test/src/main/resources/rule-tests_1_0_0.xsd
Labels: a:bug

#2344 [doc] Update ruleset examples for ant
  docs/pages/pmd/userdocs/tools/ant.md
Labels: in:documentation

#2333 [jsp] Deprecate AST constructors and setters
  docs/pages/release_notes.md
  pmd-jsp/src/main/ant/alljavacc.xml
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/JspParser.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTAttribute.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTAttributeValue.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTCData.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTCommentTag.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTCompilationUnit.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTContent.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTDeclaration.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTDoctypeDeclaration.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTDoctypeExternalId.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTElExpression.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTElement.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTHtmlScript.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTJspComment.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTJspDeclaration.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTJspDeclarations.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTJspDirective.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTJspDirectiveAttribute.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTJspDocument.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTJspExpression.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTJspExpressionInAttribute.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTJspScriptlet.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTText.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTUnparsedText.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/ASTValueBinding.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/AbstractJspNode.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/OpenTagRegister.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/StartAndEndTagMismatchException.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/ast/SyntaxErrorException.java
Labels: is:deprecation

#2343 [ci] Disable checking for snapshots in jcenter
  pom.xml
Labels: in:pmd-internals

#2303 [vm] Deprecate AST constructors / setters
  docs/pages/release_notes.md
  pmd-vm/etc/grammar/VmParser.jjt
  pmd-vm/src/main/ant/alljavacc.xml
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/VmHandler.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/VmLanguageModule.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/VmParser.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/VmTokenManager.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/ASTAddNode.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/ASTDirective.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/ASTDivNode.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/ASTEscape.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/ASTMathNode.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/ASTMethod.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/ASTModNode.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/ASTMulNode.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/ASTReference.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/ASTStringLiteral.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/ASTSubtractNode.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/AbstractVmNode.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/MacroParseException.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/NodeUtils.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/TemplateParseException.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/TokenMgrError.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/ast/VmNode.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/directive/Block.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/directive/BlockMacro.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/directive/Break.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/directive/Define.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/directive/Directive.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/directive/Evaluate.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/directive/Foreach.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/directive/Include.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/directive/InputBase.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/directive/Literal.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/directive/Macro.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/directive/Parse.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/directive/RuntimeMacro.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/directive/Stop.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/directive/VelocimacroProxy.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/util/DirectiveMapper.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/util/LogUtil.java
Labels: is:deprecation

#2335 [plsql] Deprecate AST constructors and setters
  docs/pages/release_notes.md
  pmd-plsql/src/main/ant/alljavacc.xml
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/PLSQLParser.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/PLSQLTokenManager.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTArguments.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTComparisonCondition.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTCompoundCondition.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTDatatype.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTFormalParameter.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTIfStatement.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTInlineConstraint.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTInnerCrossJoinClause.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTInput.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTMethodDeclaration.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTMethodDeclarator.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTName.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTOutOfLineConstraint.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTOuterJoinClause.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTOuterJoinType.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTPackageBody.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTPackageSpecification.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTPrimaryPrefix.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTPrimarySuffix.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTProgramUnit.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTQueryBlock.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTRegexpLikeCondition.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTSelectIntoStatement.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTSelectStatement.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTSubqueryOperation.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTTriggerTimingPointSection.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTTriggerUnit.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTTypeMethod.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTTypeSpecification.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/ASTVariableOrConstantDeclaratorId.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/AbstractPLSQLNode.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/ast/AbstractSelectStatement.java
Labels: is:deprecation

#2334 [visualforce] Deprecate AST constructors and setters
  docs/pages/release_notes.md
  pmd-visualforce/src/main/ant/alljavacc.xml
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/VfParser.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/VfTokenManager.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/ASTArguments.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/ASTAttribute.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/ASTAttributeValue.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/ASTCData.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/ASTCompilationUnit.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/ASTContent.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/ASTDeclaration.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/ASTDoctypeDeclaration.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/ASTDoctypeExternalId.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/ASTDotExpression.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/ASTElExpression.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/ASTElement.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/ASTExpression.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/ASTHtmlScript.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/ASTIdentifier.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/ASTLiteral.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/ASTNegationExpression.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/ASTText.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/AbstractVFNode.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/OpenTagRegister.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/StartAndEndTagMismatchException.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/ast/SyntaxErrorException.java
Labels: is:deprecation

#2314 [doc] maven integration - Add version to plugin
  docs/pages/pmd/userdocs/tools/maven.md
Labels: in:documentation, is:WIP

#2382 [core] Saxon rulechain excludes for path expressions
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQuery.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/ExpressionPrinter.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/RuleChainAnalyzer.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/SaxonExprVisitor.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/SplitUnions.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/DummyLanguageModule.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQueryTest.java
Labels: for:performance

#2381 [java] Refactor java processing into a context object
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTCompilationUnit.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AbstractJavaNode.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/JavaAstProcessor.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/JavaProcessingStage.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/multifile/signature/JavaOperationSignature.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JClassSymbol.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/SymbolResolver.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/impl/SymbolFactory.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/impl/UnresolvedClassImpl.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/impl/UnresolvedSymFactory.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/impl/ast/AstSymFactory.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/impl/ast/AstSymbolMakerVisitor.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/impl/ast/MapSymResolver.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/impl/ast/SymbolResolutionPass.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/impl/reflect/ClasspathSymbolResolver.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SemanticChecksLogger.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SymbolTableHelper.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SymbolTableResolver.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/JavaParsingHelper.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/Java14PreviewTest.java
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/KotlinTestingDsl.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/NodeParsingCtx.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ParserTestSpec.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/AstSymbolResolverTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/ClassPathSymbolResolverTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/UnresolvedClassTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/impl/UnresolvedClassTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/table/internal/HeaderScopesTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/table/internal/Utils.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/table/internal/VarScopingTest.kt
  pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/AstMatcherDslAdapter.kt
Labels: in:symbol-table
