Repository pmd/pmd, pull requests merged in 2020-06, with the labels that each got.

#2552 [doc] Update next major development page for PMD 7 plans
  do-release.sh
  docs/pages/next_major_development.md
Labels: in:documentation

#2573 [java] DefaultPackage: Allow package default JUnit 5 Test methods
  pmd-java/src/main/resources/category/java/codestyle.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/DefaultPackage.xml
Labels: an:enhancement

#2609 [core] Deprecate support for List attributes with XPath 2.0
  docs/pages/pmd/userdocs/extending/writing_xpath_rules.md
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/Attribute.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/AttributeAxisIterator.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/DummyNodeWithListAndEnum.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/XPathRuleTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/JaxenXPathRuleQueryTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQueryTest.java
Labels: is:deprecation

#2608 [apex][plsql][java] Deprecate base rule classes
  docs/pages/release_notes.md
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/AbstractApexUnitTestRule.java
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/ApexXPathRule.java
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/design/AbstractNcssCountRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractIgnoredAnnotationRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractInefficientZeroCheck.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJUnitRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractJavaMetricsRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractLombokAwareRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/AbstractPoorMethodCall.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/SymbolTableTestRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AbstractSunSecureRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/AbstractNcssCountRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/documentation/AbstractCommentRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/AbstractOptimizationRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/regex/RegexHelper.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/design/AbstractNcssCountRule.java
Labels: is:deprecation

#2574 [java] New Performance Rule UseIOStreamsWithApacheCommonsFileItem
  docs/pages/release_notes.md
  pmd-core/src/main/resources/rulesets/releases/6250.xml
  pmd-java/src/main/resources/category/java/performance.xml
  pmd-java/src/main/resources/rulesets/java/quickstart.xml
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/UseIOStreamsWithApacheCommonsFileItemTest.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/UseIOStreamsWithApacheCommonsFileItem.xml
Labels: a:new-rule
