Repository pmd/pmd, pull requests merged in 2020-10, with the labels that each got.

#2831 [core] Fix XMLRenderer newlines when running under IBM Java
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/XMLRenderer.java
Labels: a:bug

#2824 [doc] Include deprecated rule references in documentation (Fixes #2823)
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java
  pmd-core/src/main/java/net/sourceforge/pmd/RulesetsFactoryUtils.java
  pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryTest.java
  pmd-doc/src/main/java/net/sourceforge/pmd/docs/GenerateRuleDocsCmd.java
  pmd-doc/src/test/java/net/sourceforge/pmd/docs/RuleDocGeneratorTest.java
  pmd-doc/src/test/resources/expected/java.md
  pmd-doc/src/test/resources/expected/sample.md
  pmd-doc/src/test/resources/rulesets/ruledoctest/sample.xml
Labels: in:documentation

#2870 [lang-test] Upgrade Kotlin, Dokka and Kotest
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ParserTestSpec.kt
  pmd-lang-test/pom.xml
  pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/IntelliMarker.kt
  pom.xml
Labels: dependencies

#2872 [core] Test some XPath corner cases
  docs/pages/pmd/userdocs/extending/writing_xpath_rules.md
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/internal/AstNodeOwner.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/saxon/DocumentNode.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/xpath/saxon/ElementNode.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQuery.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/SaxonXPathRuleQueryTest.java
Labels: in:xpath
