Repository pmd/pmd, pull requests merged in 2020-11, with the labels that each got.

#2888 [java] Deprecations for #2887 (replace some attributes with getName)
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTCompilationUnit.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTPackageDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTTypeParameter.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/qname/QualifiedNameResolver.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/LoosePackageCouplingRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/UselessOverridingMethodRule.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ASTPackageDeclarationTest.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java15p/Records.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java15p/expression/Expr.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java15p/geometry/Shape.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java15p/geometry/Square.txt
Labels: in:ast, is:deprecation

#2887 [java] Add some methods to java AST
  .travis/secrets.tar.enc
  .travis/setup-secrets.sh
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/impl/AttributeAxisIterator.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTCompilationUnit.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTMethodDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTNumericLiteral.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTPackageDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTStringLiteral.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTSwitchBranch.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTTypeParameter.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableDeclarator.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableDeclaratorId.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AccessNode.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/FinalizableNode.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JModifier.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/UnnecessaryFullyQualifiedNameRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/UselessOverridingMethodRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/ast/AstTypeParamSym.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symboltable/ScopeAndDeclarationFinder.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ASTPackageDeclarationTest.java
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTLiteralTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ModifiersTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/TestExtensions.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/TypeTestMockingUtil.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/SpecialMethodsTest.kt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/Bug1429.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/Bug1530.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/EmptyStmts1.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/EmptyStmts2.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/EmptyStmts3.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/GitHubBug207.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/GitHubBug208.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/GitHubBug309.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/LambdaBug1333.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/LambdaBug1470.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/LambdaBug206.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/ParserCornerCases.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/ParserCornerCases17.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/ParserCornerCases18.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/SwitchStatements.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/SwitchWithFallthrough.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/SynchronizedStmts.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java15/NonSealedIdentifier.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java15/TextBlocks.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java15p/LocalInterfacesAndEnums.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java15p/LocalRecords.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java15p/PatternMatchingInstanceof.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java15p/Records.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java15p/expression/Expr.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java15p/geometry/Shape.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java15p/geometry/Square.txt
Labels: in:ast

#2907 [core] Deprecations for ParametricRuleViolation and ParserOptions#suppressMarker
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ParserOptions.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/ParametricRuleViolation.java
  pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/rule/ModelicaRuleViolationFactory.java
Labels: is:deprecation

#2912 [java] Deprecations for #905
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTClassOrInterfaceBody.java
Labels: is:deprecation

#2938 [cs] CPD: fix issue where ignoring using directives could not be disabled
  pmd-cs/src/main/java/net/sourceforge/pmd/cpd/CsTokenizer.java
Labels: a:bug

#2874 [core] Fix XMLRenderer with UTF-16
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/XMLRenderer.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/XMLRendererTest.java
Labels: a:bug

#2936 [java] (doc) Fix typo: "an accessor" not "a"
  pmd-java/src/main/resources/category/java/bestpractices.xml
Labels: in:documentation

#2917 [java] New Java XPath functions
  docs/_data/xpath_funs.yml
  pmd-core/src/main/java/net/sourceforge/pmd/internal/util/AssertionUtil.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/XPathRule.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/PmdXPathException.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/SaxonXPathRuleQuery.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/CollectionUtil.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/internal/SaxonXPathRuleQueryTest.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnyTypeDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTEnumConstant.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTImportDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTLocalVariableDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTSwitchLike.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/JavaAstProcessor.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/JavaDesignerBindings.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/JavaLanguageHandler.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/xpath/internal/BaseContextNodeTestFun.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/xpath/internal/BaseRewrittenFunction.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/xpath/internal/GetModifiersFun.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/xpath/internal/MatchesSignatureFunction.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/xpath/internal/MetricFunction.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/xpath/internal/NodeIsFunction.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SymTableFactory.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/table/internal/SymbolTableResolver.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeOps.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeSystem.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeTestUtil.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypesFromReflection.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/xpath/internal/BaseXPathFunctionTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/xpath/internal/GetModifiersFunctionsTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/xpath/internal/HasAnnotationXPathTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/xpath/internal/MatchesSignatureXPathTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/xpath/internal/NodeIsFunctionTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/xpath/internal/XPathMetricFunctionTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/types/InvocationMatcherTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/types/TypeTestUtilTest.java
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/TypeDisambiguationTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/AnonCtorsTest.kt
  pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/BaseParsingHelper.kt
Labels: an:enhancement, in:xpath
