Repository pmd/pmd, pull requests merged in 2021-06, with the labels that each got.

#3322 [apex] added rule to detect inaccessible AuraEnabled getters
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/errorprone/InaccessibleAuraEnabledGetterRule.java
  pmd-apex/src/main/resources/category/apex/errorprone.xml
  pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/errorprone/InaccessibleAuraEnabledGetterTest.java
  pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/errorprone/xml/InaccessibleAuraEnabledGetter.xml
Labels: a:new-rule

#3320 [java] Fix incorrect increment for "else if" branch in Cognitive Complexity docs
  pmd-java/src/main/resources/category/java/design.xml
Labels: in:documentation

#3337 [java] LiteralsFirstInComparisons false positive with two constants
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/LiteralsFirstInComparisonsRule.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/LiteralsFirstInComparisons.xml
Labels: a:false-positive

#3343 [java] CloneMethodMustImplementCloneable: FN with local classes
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloneMethodMustImplementCloneableRule.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloneMethodMustImplementCloneable.xml
Labels: a:false-negative

#3344 [java] InefficientEmptyStringCheck FN with trim.length on method call
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/InefficientEmptyStringCheckRule.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/inefficientemptystringcheck/StringTrimIsEmpty.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/inefficientemptystringcheck/StringTrimLength.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/performance/inefficientemptystringcheck/StringTrimMethodArgument.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/InefficientEmptyStringCheck.xml
Labels: a:false-negative

#3345 [java] UseArraysAsList false negative with for-each loop
  docs/pages/release_notes.md
  pmd-java/src/main/resources/category/java/performance.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/UseArraysAsList.xml
Labels: a:false-negative
