Repository pmd/pmd, pull requests merged in 2021-01, with the labels that each got.

#2994 [core] Fix code climate severity strings
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/CodeClimateRenderer.java
Labels: a:bug

#3000 [ci] Fixes for pmdtester (baseline, danger)
  .ci/inc/regression-tester.inc
  .github/workflows/pull-requests.yml
  Dangerfile
Labels: github_actions

#3060 [java] Fix threading issue in MethodNamingConventionsRule
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/MethodNamingConventionsRule.java
Labels: a:bug

#3066 [java] Make unused rules ignore some names
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedAssignmentRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedFormalParameterRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedLocalVariableRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/JavaRuleUtil.java
  pmd-java/src/main/resources/category/java/bestpractices.xml
  pmd-java/src/test/java/net/sourceforge/pmd/ant/PMDTaskTest.java
  pmd-java/src/test/resources/ant/java/EncodingTestClass.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedAssignment.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedFormalParameter.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedLocalVariable.xml
Labels: an:enhancement

#3069 [xml] Deprecate xml base rule classes
  docs/pages/release_notes.md
  pmd-xml/src/main/java/net/sourceforge/pmd/lang/wsdl/rule/AbstractWsdlRule.java
  pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/rule/AbstractDomXmlRule.java
  pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/rule/AbstractXmlRule.java
Labels: is:deprecation

#3072 [java] Deprecate some performance rules
  docs/pages/release_notes.md
  pmd-java/src/main/resources/category/java/performance.xml
Labels: is:deprecation
