Repository pmd/pmd, pull requests merged in 2021-07, with the labels that each got.

#3360 [ci] Add openjdk-11 as pmd-regression-tester project
  .ci/files/project-list.xml
Labels: in:pmd-internals

#3385 [core] CPD: Optimize --skip-lexical-errors option
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPD.java
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/TokenEntry.java
Labels: for:performance, in:cpd

#3388 [doc] Add Code Inspector in the list of tools
  docs/pages/pmd/userdocs/tools/tools.md
Labels: in:documentation

#3392 [ci] Run PMD on PMD with the latest snapshot
  .ci/build.sh
  pom.xml
Labels: in:pmd-internals

#3410 [ci] Fetch more commits for danger and regression tester
  .ci/inc/regression-tester.inc
Labels: in:pmd-internals

#3365 [java] New rule PrimitiveWrapperInstantiation
  docs/pages/release_notes.md
  pmd-core/src/main/resources/rulesets/releases/6370.xml
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/PrimitiveWrapperInstantiationRule.java
  pmd-java/src/main/resources/category/java/bestpractices.xml
  pmd-java/src/main/resources/category/java/performance.xml
  pmd-java/src/main/resources/rulesets/java/quickstart.xml
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/PrimitiveWrapperInstantiationTest.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/PrimitiveWrapperInstantiation.xml
Labels: a:new-rule, is:deprecation
