Repository pmd/pmd, pull requests merged in 2021-02, with the labels that each got.

#3107 [plsql] Fix ParseException for EXECUTE IMMEDIATE str1||str2;
  pmd-plsql/etc/grammar/PldocAST.jjt
  pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/PLSQLParserTest.java
  pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/ast/ExecuteImmediateIssue3106.pls
Labels: in:grammar

#3115 [ci] Stop logging download progress in CI
  .ci/build-pr-win-macos.sh
  .ci/build.sh
  .ci/inc/maven-dependencies.inc
Labels: github_actions

#3137 [java] Deprecation in AvoidUsingHardCodedIPRule
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/AvoidUsingHardCodedIPRule.java
Labels: is:deprecation
