Repository pmd/pmd, pull requests merged in 2021-05, with the labels that each got.

#3265 [java] MethodArgumentCouldBeFinal: false negatives with interfaces and inner classes
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/MethodArgumentCouldBeFinalRule.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/AvoidReassigningLoopVariables.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/MethodArgumentCouldBeFinal.xml
Labels: a:false-negative

#3266 [java] LocalVariableCouldBeFinal: false negatives with interfaces, anon classes
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/LocalVariableCouldBeFinalRule.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/LocalVariableCouldBeFinal.xml
Labels: a:false-negative

#3237 [java] Improve CompareObjectsWithEquals
  pmd-java/src/main/resources/category/java/errorprone.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CompareObjectsWithEquals.xml
Labels: an:enhancement

#3249 [java] AvoidFieldNameMatchingTypeName: False negative with interfaces
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/AvoidFieldNameMatchingTypeNameRule.java
  pmd-java/src/main/resources/category/java/errorprone.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidFieldNameMatchingTypeName.xml
Labels: a:false-negative

#3268 [java] ConstructorCallsOverridableMethod: IndexOutOfBoundsException with annotations
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/ConstructorCallsOverridableMethodRule.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/ConstructorCallsOverridableMethod.xml
Labels: a:bug

#3274 [java] OnlyOneReturn: false negative with anonymous class
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/OnlyOneReturnRule.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/OnlyOneReturn.xml
Labels: a:false-negative
