Repository pmd/pmd, pull requests merged in 2022-04, with the labels that each got.

#3889 [java] Catch LinkageError in UselessOverridingMethodRule
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/UselessOverridingMethodRule.java
Labels: a:bug

#3883 [doc] Improve side bar by Adding Release Date
  docs/_includes/sidebar.html
  docs/css/pmd-customstyles.css
  docs/css/theme-blue.css
  docs/css/theme-green.css
Labels: in:documentation

#3890 [java] Improve module grammar
  pmd-java/etc/grammar/Java.jjt
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTCompilationUnit.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTModuleDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTModuleDirective.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTModuleExportsDirective.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTModuleName.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTModuleOpensDirective.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTModuleProvidesDirective.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTModuleRequiresDirective.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTModuleUsesDirective.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTName.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTPackageDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTYieldStatement.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AbstractPackageNameModuleDirective.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/LooseCouplingRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/ast/LazyTypeResolver.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ASTModuleDeclarationTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/JDKVersionTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/Java9TreeDumpTest.java
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTModuleDeclarationTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/KotlinTestingDsl.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/NodeParsingCtx.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/TypeDisambiguationTest.kt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java9/jdk9_anonymous_diamond.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java9/jdk9_invalid_identifier.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java9/jdk9_module_info.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java9/jdk9_module_info.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java9/jdk9_module_info_with_annot.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java9/jdk9_module_info_with_annot.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java9/jdk9_private_interface_methods.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java9/jdk9_try_with_resources.java
Labels: in:grammar

#3912 [java] Fix IndexOutOfBoundsException with lambda that has wrong shape
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTLambdaExpression.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTLambdaParameter.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/ast/LazyTypeResolver.java
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/UnresolvedTypesRecoveryTest.kt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/LambdaBug1333.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/LambdaBug1470.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/ParserCornerCases18.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java14/YieldStatements.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ast/jdkversiontests/java16/LocalRecords.txt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/ReturnEmptyCollectionRatherThanNull.xml
Labels: a:bug

#3943 chore: Set permissions for GitHub actions
  .github/workflows/troubleshooting.yml
Labels: in:pmd-internals

#3939 [test] Print Test Method Name for failed rule tests
  pmd-test/src/main/java/net/sourceforge/pmd/testframework/PMDTestRunner.java
  pmd-test/src/main/java/net/sourceforge/pmd/testframework/RuleTestRunner.java
  pmd-test/src/main/java/net/sourceforge/pmd/testframework/RuleTst.java
  pmd-test/src/main/java/net/sourceforge/pmd/testframework/TestDescriptor.java
  pmd-test/src/test/java/net/sourceforge/pmd/testframework/TestDescriptorTest.java
Labels: in:pmd-internals
