Repository pmd/pmd, pull requests merged in 2022-02, with the labels that each got.

#3762 [core] Deprecations for analysis listeners
  docs/pages/release_notes.md
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/documentation/ApexDocRule.java
  pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/SuppressWarningsTest.java
  pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/AbstractApexRuleTest.java
  pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/security/ApexSharingViolationsNestedClassTest.java
  pmd-core/src/main/java/net/sourceforge/pmd/Report.java
  pmd-core/src/main/java/net/sourceforge/pmd/RuleContext.java
  pmd-core/src/main/java/net/sourceforge/pmd/RuleSet.java
  pmd-core/src/main/java/net/sourceforge/pmd/ThreadSafeReportListener.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRule.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractRuleChainVisitor.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/RuleViolationFactory.java
  pmd-core/src/test/java/net/sourceforge/pmd/AbstractRuleTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/XPathRuleTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/stat/MockStatisticalRule.java
  pmd-core/src/test/java/net/sourceforge/pmd/stat/StatisticalRuleTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/SuppressWarningsTest.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/codestyle/AvoidTabCharacterRule.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/codestyle/LineLengthRule.java
  pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/PLSQLXPathRuleTest.java
  pmd-scala-modules/pmd-scala-common/src/test/java/net/sourceforge/pmd/lang/scala/rule/ScalaRuleTest.java
Labels: is:deprecation

#3781 [core] Fix #3427 - Stop printing usage text on error
  pmd-core/src/main/java/net/sourceforge/pmd/PMD.java
  pmd-core/src/main/java/net/sourceforge/pmd/cli/internal/CliMessages.java
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDCommandLineInterface.java
  pmd-core/src/test/java/net/sourceforge/pmd/cli/CoreCliTest.java
  pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java
  pmd-dist/src/test/java/net/sourceforge/pmd/it/CpdExecutor.java
  pmd-dist/src/test/java/net/sourceforge/pmd/it/ExecutionResult.java
  pmd-dist/src/test/java/net/sourceforge/pmd/it/PMDExecutor.java
  pmd-dist/src/test/resources/sample-source/unparsable/cannot_be_parsed.java
Labels: an:enhancement, in:cli

#3807 [doc] Document Ant Task parameter `threads`
  docs/pages/pmd/userdocs/tools/ant.md
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/ant/PMDTask.java
  pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDParameters.java
Labels: in:documentation
