Repository pmd/pmd, pull requests merged in 2022-05, with the labels that each got.

#3960 [core] Support globs in CLI
  docs/pages/pmd/userdocs/cli_reference.md
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/PMDConfiguration.java
  pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDParameters.java
  pmd-core/src/main/java/net/sourceforge/pmd/cli/PmdParametersParseResult.java
  pmd-core/src/test/java/net/sourceforge/pmd/cli/CoreCliTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/cli/PMDParametersTest.java
  pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java
Labels: an:enhancement, in:cli

#3967 Bump kotlin from 1.4.10 to 1.4.32
  pom.xml
Labels: dependencies

#3958 [core] Deprecate some syntax for ruleset references
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/PMD.java
  pmd-core/src/main/java/net/sourceforge/pmd/RuleSetFactory.java
  pmd-core/src/main/java/net/sourceforge/pmd/RuleSetLoader.java
  pmd-core/src/main/java/net/sourceforge/pmd/RuleSetReferenceId.java
  pmd-core/src/test/java/net/sourceforge/pmd/RuleSetFactoryTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/cli/CoreCliTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/cli/CLITest.java
Labels: is:deprecation, in:ruleset-xml

#3978 [html] Add additional file extensions htm, xhtml, xht, shtml
  docs/pages/release_notes.md
  pmd-html/src/main/java/net/sourceforge/pmd/lang/html/HtmlLanguageModule.java
Labels: an:enhancement

#3979 [core] Internalize CPDCommandLineInterface
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPD.java
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDCommandLineInterface.java
  pmd-core/src/test/java/net/sourceforge/pmd/cpd/CPDCommandLineInterfaceTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/cpd/CPDCommandLineInterfaceTest.java
  pmd-javascript/src/test/java/net/sourceforge/pmd/cpd/CPDCommandLineInterfaceTest.java
  pmd-test/src/main/java/net/sourceforge/pmd/cli/BaseCPDCLITest.java
Labels: is:deprecation

#3980 [core] Internalize some methods in Ant Formatter
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/ant/Formatter.java
Labels: is:deprecation
