Repository pmd/pmd, pull requests merged in 2022-11, with the labels that each got.

#4184 [java][doc] TestClassWithoutTestCases - fix small typo in description
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/TestClassWithoutTestCasesRule.java
Labels: in:documentation

#4198 [doc] Add supported CPD languages
  docs/pages/pmd/userdocs/cpd/cpd.md
Labels: in:documentation

#4205 [doc] Clarify Scala support (no built-in rules)
  README.md
  package-lock.json
Labels: in:documentation

#4207 [doc] List all languages in rule doc
  docs/_data/sidebars/pmd_sidebar.yml
  pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleDocGenerator.java
  pmd-doc/src/test/java/net/sourceforge/pmd/docs/SidebarGeneratorTest.java
  pmd-doc/src/test/resources/expected/pmd_sidebar.yml
  pmd-doc/src/test/resources/net/sourceforge/pmd/docs/sidebar.yml
Labels: in:documentation

#4203 [java] New Rule InvalidJavaBean
  docs/pages/release_notes.md
  pmd-core/src/main/resources/rulesets/releases/6520.xml
  pmd-doc/src/main/java/net/sourceforge/pmd/docs/RuleDocGenerator.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/InvalidJavaBeanRule.java
  pmd-java/src/main/resources/category/java/design.xml
  pmd-java/src/main/resources/rulesets/java/quickstart.xml
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/design/InvalidJavaBeanTest.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/InvalidJavaBean.xml
Labels: a:new-rule

#4232 [doc] Fixing typos
  docs/pages/pmd/devdocs/major_contributions/adding_new_cpd_language.md
  docs/pages/pmd/projectdocs/committers/releasing.md
  docs/pages/pmd/projectdocs/credits.md
  docs/pages/pmd/projectdocs/trivia/similarprojects.md
  docs/pages/pmd/userdocs/extending/metrics_howto.md
  docs/pages/pmd/userdocs/making_rulesets.md
  docs/pages/release_notes.md
  docs/pages/release_notes_old.md
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/dfa/StatementAndBraceFinder.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/rule/codestyle/CodeFormatRule.java
  pmd-plsql/src/test/resources/net/sourceforge/pmd/lang/plsql/rule/codestyle/xml/CodeFormat.xml
Labels: in:documentation

#4243 [java] Expose symbol annotations
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/NodeStream.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/CollectionUtil.java
  pmd-java/pom.xml
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnnotation.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnnotationMemberList.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTSwitchLike.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ClassWithOnlyPrivateConstructorsShouldBeFinalRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/AnnotationSuppressionUtil.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/AnnotWrapper.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/AnnotableSymbol.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JAccessibleElementSymbol.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JClassSymbol.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JElementSymbol.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JExecutableSymbol.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JMethodSymbol.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JVariableSymbol.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/SymbolicValue.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/SymbolEquality.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/AnnotationBuilderVisitor.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/AnnotationOwner.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassNamesUtil.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStub.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStubBuilder.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ExecutableStub.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/MemberStubBase.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/MethodInfoVisitor.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/SymbolicAnnotationImpl.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/SymbolicValueBuilder.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/ast/AbstractAstExecSymbol.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/ast/AbstractAstVariableSym.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/ast/AstClassSym.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/ast/AstMethodSym.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/ast/AstSymbolicAnnot.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/FakeIntersectionSymbol.java
  pmd-java/src/test/java/javasymbols/testdata/impls/AnnotationTests.java
  pmd-java/src/test/java/javasymbols/testdata/impls/SomeFields.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ASTSwitchLabelTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/AbstractSymbolTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/SymbolParsingTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/SymbolReflectionTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/SymbolicValueTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/testdata/AnnotWithDefaults.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/testdata/ConstructorAnnotation.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/testdata/FieldAnnotation.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/testdata/LocalVarAnnotation.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/testdata/MethodAnnotation.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/testdata/ParameterAnnotation.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/testdata/SomeClass.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/testdata/TypeAnnotation.java
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/ReflectedFieldSymbolTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/asm/AsmLoaderTest.kt
Labels: in:type-resolution, in:symbol-table
