Repository pmd/pmd, pull requests merged in 2022-03, with the labels that each got.

#3773 [apex] EagerlyLoadedDescribeSObjectResult false positives with SObjectField.getDescribe()
  .all-contributorsrc
  docs/pages/pmd/projectdocs/credits.md
  docs/pages/release_notes.md
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTReferenceExpression.java
  pmd-apex/src/main/resources/category/apex/performance.xml
  pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/ast/SafeNavigationOperator.txt
  pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/performance/xml/EagerlyLoadedDescribeSObjectResult.xml
Labels: a:false-positive

#3827 [java] Fix handling of classes with dollars in their names
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/internal/JavaAstProcessor.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/AsmSymbolResolver.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStub.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStubBuilder.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/Loader.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/SoftClassReference.java
  pmd-java/src/test/java/javasymbols/testdata/deep/AClassWithLocals.java
  pmd-java/src/test/java/javasymbols/testdata/deep/Another$ClassWith$Dollar.java
  pmd-java/src/test/java/javasymbols/testdata/deep/ClassWithDollar$.java
  pmd-java/src/test/java/javasymbols/testdata/deep/OuterWithoutDollar.java
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/asm/AsmLoaderTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/asm/BrokenClasspathTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/asm/NamesTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/table/internal/HeaderScopesTest.kt
  pmd-test/src/main/java/net/sourceforge/pmd/testframework/RuleTst.java
Labels: in:symbol-table

#3833 [core] Update saxon to 10.7
  pom.xml
Labels: in:xpath

#3817 [apex] Add designer bindings to display main attributes
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ApexHandler.java
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/internal/ApexDesignerBindings.java
Labels: an:enhancement

#3818 [core] Fix abstract ruleset factory test
  docs/pages/release_notes.md
  pmd-modelica/pom.xml
  pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/rule/AmbiguousResolutionRule.java
  pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/rule/ConnectUsingNonConnector.java
  pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/rule/bestpractices/AmbiguousResolutionRule.java
  pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/rule/bestpractices/ConnectUsingNonConnectorRule.java
  pmd-modelica/src/main/resources/category/modelica/bestpractices.xml
  pmd-test/src/main/java/net/sourceforge/pmd/AbstractRuleSetFactoryTest.java
Labels: in:pmd-internals, is:deprecation

#3856 [ci] Fix project-list for spring
  .ci/files/project-list.xml
Labels: in:pmd-internals
