Repository pmd/pmd, pull requests merged in 2023-02, with the labels that each got.

#4384 [swift] Add more swift 5.x support (#unavailable mainly)
  pmd-swift/src/main/antlr4/net/sourceforge/pmd/lang/swift/antlr4/Swift.g4
  pmd-swift/src/test/java/net/sourceforge/pmd/cpd/SwiftTokenizerTest.java
  pmd-swift/src/test/resources/net/sourceforge/pmd/lang/swift/cpd/testdata/Swift5.3.swift
  pmd-swift/src/test/resources/net/sourceforge/pmd/lang/swift/cpd/testdata/Swift5.3.txt
  pmd-swift/src/test/resources/net/sourceforge/pmd/lang/swift/cpd/testdata/Swift5.5.swift
  pmd-swift/src/test/resources/net/sourceforge/pmd/lang/swift/cpd/testdata/Swift5.5.txt
  pmd-swift/src/test/resources/net/sourceforge/pmd/lang/swift/cpd/testdata/Swift5.6.swift
  pmd-swift/src/test/resources/net/sourceforge/pmd/lang/swift/cpd/testdata/Swift5.6.txt
Labels: an:enhancement

#4374 [go] Deprecate GoLanguageModule
  docs/pages/release_notes.md
  pmd-go/src/main/java/net/sourceforge/pmd/lang/go/GoLanguageModule.java
  pmd-go/src/test/java/net/sourceforge/pmd/LanguageVersionTest.java
Labels: is:deprecation

#4386 Update versions
  .mvn/wrapper/maven-wrapper.properties
  pom.xml
Labels: in:pmd-internals, dependencies

#4398 [doc] CPD - use non deprecated `--dir` cli option
  docs/pages/pmd/userdocs/cpd/cpd.md
  docs/pages/pmd/userdocs/installation.md
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDCommandLineInterface.java
  pmd-core/src/test/java/net/sourceforge/pmd/cpd/CPDCommandLineInterfaceTest.java
  pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java
  pmd-java/src/test/java/net/sourceforge/pmd/cpd/CPDCommandLineInterfaceTest.java
  pmd-javascript/src/test/java/net/sourceforge/pmd/cpd/CPDCommandLineInterfaceTest.java
Labels: in:documentation

#4395 [core] Support environment variable CLASSPATH with pmd.bat under Windows
  docs/pages/pmd/userdocs/cli_reference.md
  docs/pages/release_notes.md
  pmd-dist/src/main/resources/scripts/pmd.bat
Labels: a:bug

#4407 [doc] Update release notes - last pmd6 release, pmd7 development
  docs/pages/release_notes.md
Labels: in:documentation

#4399 [test] Remove dummy language module from pmd-test
  pmd-test/pom.xml
  pmd-test/src/main/java/net/sourceforge/pmd/test/lang/DummyLanguageModule.java
  pmd-test/src/main/java/net/sourceforge/pmd/test/lang/ast/DummyNode.java
  pmd-test/src/main/java/net/sourceforge/pmd/testframework/RuleTst.java
  pmd-test/src/main/java/net/sourceforge/pmd/testframework/SimpleAggregatorTst.java
  pmd-test/src/main/resources/META-INF/services/net.sourceforge.pmd.lang.Language
  pmd-test/src/test/java/net/sourceforge/pmd/testframework/RuleTstTest.java
Labels: is:feature-removal, in:testing

#4362 [core] Allow more XPath rules to use the rulechain
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/SaxonExprTransformations.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/SaxonXPathRuleQuery.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/SplitUnions.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/internal/SaxonXPathRuleQueryTest.java
Labels: for:performance, in:xpath

#4387 [core] Explicitly name all language versions
  docs/_data/sidebars/pmd_sidebar.yml
  docs/pages/7_0_0_release_notes.md
  docs/pages/pmd/userdocs/cli_reference.md
  docs/pages/pmd/userdocs/tools/ant.md
  pmd-apex/src/main/java/net/sourceforge/pmd/cpd/ApexLanguage.java
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ApexLanguageModule.java
  pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/LanguageVersionTest.java
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/AbstractLanguage.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/LanguageModuleBase.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/PlainTextLanguage.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/LanguageModuleBaseTest.java
  pmd-dist/src/test/java/net/sourceforge/pmd/it/AllRulesIT.java
  pmd-dist/src/test/java/net/sourceforge/pmd/it/AnalysisCacheIT.java
  pmd-dist/src/test/java/net/sourceforge/pmd/it/AntIT.java
  pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java
  pmd-dist/src/test/java/net/sourceforge/pmd/it/ExecutionResult.java
  pmd-doc/src/test/resources/expected/pmd_sidebar.yml
  pmd-doc/src/test/resources/net/sourceforge/pmd/docs/sidebar.yml
  pmd-html/src/main/java/net/sourceforge/pmd/lang/html/HtmlCpdLanguage.java
  pmd-html/src/main/java/net/sourceforge/pmd/lang/html/HtmlLanguageModule.java
  pmd-html/src/test/java/net/sourceforge/pmd/lang/html/LanguageVersionTest.java
  pmd-java/src/main/java/net/sourceforge/pmd/cpd/JavaLanguage.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/JavaLanguageModule.java
  pmd-javascript/src/main/java/net/sourceforge/pmd/cpd/EcmascriptLanguage.java
  pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/EcmascriptLanguageModule.java
  pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/EcmascriptParser.java
  pmd-javascript/src/test/java/net/sourceforge/pmd/lang/ecmascript/LanguageVersionTest.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/cpd/JSPLanguage.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/lang/jsp/JspLanguageModule.java
  pmd-jsp/src/test/java/net/sourceforge/pmd/lang/jsp/LanguageVersionTest.java
  pmd-kotlin/src/main/java/net/sourceforge/pmd/cpd/KotlinLanguage.java
  pmd-kotlin/src/main/java/net/sourceforge/pmd/lang/kotlin/KotlinLanguageModule.java
  pmd-kotlin/src/test/java/net/sourceforge/pmd/lang/kotlin/LanguageVersionTest.java
  pmd-modelica/src/main/java/net/sourceforge/pmd/cpd/ModelicaLanguage.java
  pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/ModelicaLanguageModule.java
  pmd-modelica/src/test/java/net/sourceforge/pmd/lang/modelica/LanguageVersionTest.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/cpd/PLSQLLanguage.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/lang/plsql/PLSQLLanguageModule.java
  pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/LanguageVersionTest.java
  pmd-scala-modules/pmd-scala-common/src/main/java/net/sourceforge/pmd/cpd/ScalaLanguage.java
  pmd-scala-modules/pmd-scala-common/src/main/java/net/sourceforge/pmd/lang/scala/ScalaLanguageModule.java
  pmd-swift/src/main/java/net/sourceforge/pmd/cpd/SwiftLanguage.java
  pmd-swift/src/main/java/net/sourceforge/pmd/lang/swift/SwiftLanguageModule.java
  pmd-swift/src/test/java/net/sourceforge/pmd/lang/swift/LanguageVersionTest.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/cpd/VfLanguage.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/VfLanguageModule.java
  pmd-visualforce/src/test/java/net/sourceforge/pmd/lang/vf/LanguageVersionTest.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/VmLanguageModule.java
  pmd-vm/src/test/java/net/sourceforge/pmd/lang/vm/LanguageVersionTest.java
  pmd-xml/src/main/java/net/sourceforge/pmd/lang/pom/PomLanguageModule.java
  pmd-xml/src/main/java/net/sourceforge/pmd/lang/wsdl/WsdlLanguageModule.java
  pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/XmlLanguageModule.java
  pmd-xml/src/main/java/net/sourceforge/pmd/lang/xsl/XslLanguageModule.java
  pmd-xml/src/main/java/net/sourceforge/pmd/xml/cpd/XmlLanguage.java
  pmd-xml/src/test/java/net/sourceforge/pmd/lang/xml/LanguageVersionTest.java
  pmd-xml/src/test/resources/net/sourceforge/pmd/ant/xml/pmdtasktest.xml
Labels: an:enhancement
