Repository pmd/pmd, pull requests merged in 2023-03, with the labels that each got.

#4412 [doc] Added new error msg to ConstantsInInterface
  pmd-java/src/main/resources/category/java/bestpractices.xml
Labels: in:documentation

#4420 [core] Remove PMD.EOL
  docs/pages/release_notes.md
  pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/SuppressWarningsTest.java
  pmd-core/src/main/java/net/sourceforge/pmd/PMD.java
  pmd-core/src/main/java/net/sourceforge/pmd/benchmark/TextTimingReportRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/cli/PMDCommandLineInterface.java
  pmd-core/src/main/java/net/sourceforge/pmd/cli/PmdParametersParseResult.java
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/CSVRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/Match.java
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/SimpleRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/VSRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/javacc/AbstractTokenManager.java
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/AbstractRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/CSVRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/CodeClimateIssue.java
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/CodeClimateRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/HTMLRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/IDEAJRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/SummaryHTMLRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/TextColorRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/TextPadRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/TextRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/VBHTMLRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/XMLRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/YAHTMLRenderer.java
  pmd-core/src/test/java/net/sourceforge/pmd/RuleSetSchemaTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/cpd/CSVRendererTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/AbstractRendererTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/CSVRendererTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/CodeClimateRendererTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/EmacsRendererTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/HTMLRendererTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/IDEAJRendererTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/JsonRendererTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/PapariTextRendererTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/SummaryHTMLRendererTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/TextPadRendererTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/TextRendererTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/VBHTMLRendererTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/XMLRendererTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/YAHTMLRendererTest.java
  pmd-dist/src/test/java/net/sourceforge/pmd/it/ExecutionResult.java
  pmd-doc/src/test/java/net/sourceforge/pmd/docs/MockedFileWriter.java
  pmd-java/src/test/java/net/sourceforge/pmd/ReportTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/XPathRuleTest.java
  pmd-javascript/src/test/java/net/sourceforge/pmd/lang/ecmascript/ast/EcmascriptParserTest.java
  pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/BaseParsingHelper.kt
  pmd-test/src/main/java/net/sourceforge/pmd/AbstractRuleSetFactoryTest.java
Labels: is:feature-removal

#4373 [doc] Update release notes for PMD 7.0.0-rc1
  do-release.sh
  docs/_data/sidebars/pmd_sidebar.yml
  docs/images/userdocs/pmd-demo.gif
  docs/pages/7_0_0_release_notes.md
  docs/pages/pmd/userdocs/installation.md
  docs/pages/release_notes.md
  docs/pages/release_notes_pmd7.md
  docs/render_release_notes.rb
Labels: in:documentation

#4423 [cli] Fix NPE when only `--file-list` is specified
  pmd-cli/src/main/java/net/sourceforge/pmd/cli/commands/internal/PmdCommand.java
  pmd-cli/src/test/java/net/sourceforge/pmd/cli/PmdCliTest.java
Labels: a:bug

#4417 [core] [java] More micro opts
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/AstVisitorBase.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/AbstractNode.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/GenericNode.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/internal/AxisStream.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/internal/Filtermap.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/internal/StreamImpl.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/Attribute.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/impl/AttributeAxisIterator.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/AstDocumentNode.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/AstElementNode.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/AstTreeInfo.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/BaseNodeInfo.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/DummyNodeWithDeprecatedAttribute.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/internal/NodeStreamTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/lang/rule/xpath/NoAttributeTest.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTCompilationUnit.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTList.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTModifierList.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTVariableDeclaratorId.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AbstractJavaNode.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/AccessNode.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaParserVisitor.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UseTryWithResourcesRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/OverrideBothEqualsAndHashcodeRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/SymbolEquality.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/ClassTypeImpl.java
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/TokenUtilsTest.kt
Labels: for:performance
