Repository pmd/pmd, pull requests merged in 2023-09, with the labels that each got.

#4665 [java] Doc: Fix references AutoClosable -> AutoCloseable
  pmd-java/src/main/resources/category/java/errorprone.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UseTryWithResources.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml
Labels: in:documentation

#4664 [cli] CPD: Fix NPE when only `--file-list` is specified
  pmd-cli/src/main/java/net/sourceforge/pmd/cli/commands/internal/CpdCommand.java
Labels: a:bug

#4692 Bump wiremock from 2.33.2 to 2.35.1
  pom.xml
Labels: dependencies

#4693 Update gems
  Gemfile.lock
  docs/Gemfile.lock
Labels: dependencies
