Repository pmd/pmd, pull requests merged in 2023-10, with the labels that each got.

#4561 [java] New Rule: Use Explicit Types
  docs/pages/release_notes.md
  docs/pages/release_notes_pmd7.md
  pmd-core/src/main/resources/rulesets/releases/700.xml
  pmd-java/src/main/resources/category/java/codestyle.xml
  pmd-java/src/main/resources/rulesets/java/quickstart.xml
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/UseExplicitTypesTest.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UseExplicitTypes.xml
Labels: a:new-rule

#4640 [cli] Launch script fails if run via "bash pmd"
  pmd-dist/src/main/resources/scripts/pmd
Labels: a:bug

#4659 [ant] Improve documentation
  docs/pages/pmd/userdocs/cpd/cpd.md
  docs/pages/pmd/userdocs/tools/ant.md
  pmd-ant/src/main/java/net/sourceforge/pmd/ant/CPDTask.java
  pmd-ant/src/main/java/net/sourceforge/pmd/ant/PMDTask.java
Labels: in:documentation

#4661 [doc] Update language modules
  docs/_data/sidebars/pmd_sidebar.yml
  docs/_data/tags.yml
  docs/_includes/language_info.html
  docs/_plugins/javadoc_tag.rb
  docs/_plugins/jdoc_namespace_tag.rb
  docs/css/customstyles.css
  docs/css/theme-green.css
  docs/pages/pmd/devdocs/major_contributions/adding_a_new_antlr_based_language.md
  docs/pages/pmd/devdocs/major_contributions/adding_a_new_javacc_based_language.md
  docs/pages/pmd/devdocs/major_contributions/adding_new_cpd_language.md
  docs/pages/pmd/languages/apex.md
  docs/pages/pmd/languages/coco.md
  docs/pages/pmd/languages/cpp.md
  docs/pages/pmd/languages/cs.md
  docs/pages/pmd/languages/dart.md
  docs/pages/pmd/languages/fortran.md
  docs/pages/pmd/languages/gherkin.md
  docs/pages/pmd/languages/go.md
  docs/pages/pmd/languages/groovy.md
  docs/pages/pmd/languages/html.md
  docs/pages/pmd/languages/index.md
  docs/pages/pmd/languages/java.md
  docs/pages/pmd/languages/js_ts.md
  docs/pages/pmd/languages/jsp.md
  docs/pages/pmd/languages/julia.md
  docs/pages/pmd/languages/kotlin.md
  docs/pages/pmd/languages/language_properties.md
  docs/pages/pmd/languages/lua.md
  docs/pages/pmd/languages/matlab.md
  docs/pages/pmd/languages/modelica.md
  docs/pages/pmd/languages/objectivec.md
  docs/pages/pmd/languages/perl.md
  docs/pages/pmd/languages/php.md
  docs/pages/pmd/languages/plsql.md
  docs/pages/pmd/languages/python.md
  docs/pages/pmd/languages/ruby.md
  docs/pages/pmd/languages/scala.md
  docs/pages/pmd/languages/swift.md
  docs/pages/pmd/languages/tsql.md
  docs/pages/pmd/languages/visualforce.md
  docs/pages/pmd/languages/vm.md
  docs/pages/pmd/languages/xml.md
  docs/pages/tags/tag_CpdCapableLanguage.md
  docs/pages/tags/tag_PmdCapableLanguage.md
  docs/pages/tags/tag_experimental.md
  pmd-doc/src/test/resources/expected/pmd_sidebar.yml
  pmd-tsql/src/main/java/net/sourceforge/pmd/lang/tsql/TSqlLanguageModule.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/VfLanguageModule.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/vf/VfLanguageProperties.java
  pmd-vm/src/main/java/net/sourceforge/pmd/lang/vm/VmLanguageModule.java
Labels: in:documentation

#4669 [doc] Add bld PMD Extension to Tools / Integrations
  docs/_data/sidebars/pmd_sidebar.yml
  docs/pages/pmd/userdocs/tools/bld.md
Labels: in:documentation

#4673 [javascript] CPD: Added support for decorator notation
  docs/pages/release_notes.md
  pmd-javascript/etc/grammar/Ecmascript5.jj
  pmd-javascript/src/test/java/net/sourceforge/pmd/lang/ecmascript/cpd/EcmascriptTokenizerTest.java
  pmd-javascript/src/test/resources/net/sourceforge/pmd/lang/ecmascript/cpd/testdata/decorator.js
  pmd-javascript/src/test/resources/net/sourceforge/pmd/lang/ecmascript/cpd/testdata/decorator.txt
Labels: in:grammar

#4677 [apex] Add new rule: OperationWithHighCostInLoop
  docs/pages/release_notes.md
  docs/pages/release_notes_pmd7.md
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/performance/OperationWithHighCostInLoopRule.java
  pmd-apex/src/main/resources/category/apex/performance.xml
  pmd-apex/src/main/resources/rulesets/apex/quickstart.xml
  pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/rule/performance/OperationWithHighCostInLoopTest.java
  pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/performance/xml/OperationWithHighCostInLoop.xml
  pmd-core/src/main/resources/rulesets/releases/700.xml
Labels: a:new-rule
