Repository pmd/pmd, pull requests merged in 2023-04, with the labels that each got.

#4461 Disable maven-pmd-plugin option linkXRef
  pom.xml
Labels: in:pmd-internals

#4459 Introduce a pmd-languages-deps module
  docs/pages/pmd/devdocs/major_contributions/adding_a_new_antlr_based_language.md
  docs/pages/pmd/devdocs/major_contributions/adding_a_new_javacc_based_language.md
  docs/pages/pmd/devdocs/major_contributions/adding_new_cpd_language.md
  pmd-cli/pom.xml
  pmd-dist/pom.xml
  pmd-dist/src/main/resources/assemblies/pmd-bin.xml
  pmd-languages-deps/pom.xml
  pom.xml
Labels: in:pmd-internals

#4462 Provide Software Bill of Materials (SBOM)
  .ci/build.sh
  docs/pages/release_notes.md
  pmd-dist/src/main/resources/assemblies/pmd-bin.xml
  pmd-dist/src/test/java/net/sourceforge/pmd/it/BinaryDistributionIT.java
  pom.xml
Labels: an:enhancement, dependencies

#4443 [doc] Update base urls for documentation
  .ci/README.md
  .ci/build.sh
  .ci/inc/pmd-doc.inc
  .github/ISSUE_TEMPLATE/0rule_violation_false-positive.md
  .github/ISSUE_TEMPLATE/1rule_violation_false-negative.md
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/_config.yml
  docs/_plugins/rule_tag.rb
  docs/pages/pmd/projectdocs/committers/main_landing_page.md
  docs/pages/pmd/projectdocs/committers/releasing.md
  docs/pages/release_notes.md
  docs/pages/release_notes_old.md
  docs/report-examples/pmd-report.sarif.json
  docs/sitemap.xml
  docs/sitemap_generator.sh
  pmd-core/src/main/java/net/sourceforge/pmd/PmdAnalysis.java
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/CodeClimateRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/SarifRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/internal/sarif/SarifLogBuilder.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/CodeClimateRendererTest.java
  pmd-core/src/test/resources/net/sourceforge/pmd/renderers/sarif/empty.sarif.json
  pmd-core/src/test/resources/net/sourceforge/pmd/renderers/sarif/expected-configerror.sarif.json
  pmd-core/src/test/resources/net/sourceforge/pmd/renderers/sarif/expected-error-nomessage.sarif.json
  pmd-core/src/test/resources/net/sourceforge/pmd/renderers/sarif/expected-error.sarif.json
  pmd-core/src/test/resources/net/sourceforge/pmd/renderers/sarif/expected-multiple-locations.sarif.json
  pmd-core/src/test/resources/net/sourceforge/pmd/renderers/sarif/expected-multiple.sarif.json
  pmd-core/src/test/resources/net/sourceforge/pmd/renderers/sarif/expected.sarif.json
  pmd-swift/pom.xml
  pmd-swift/src/main/resources/category/swift/bestpractices.xml
  pmd-swift/src/main/resources/category/swift/errorprone.xml
  pmd-test/src/main/java/net/sourceforge/pmd/AbstractRuleSetFactoryTest.java
  pom.xml
Labels: in:documentation

#4447 [doc] Add additional logos with a square shape
  docs/_includes/footer.html
  docs/images/logo/pmd-logo-300px-squared.png
  docs/images/logo/pmd-logo-600px-squared.png
  docs/images/logo/pmd-logo-70px-squared.png
  docs/images/logo/pmd-logo-white-300px-squared.png
  docs/images/logo/pmd-logo-white-400x165px.png
  docs/images/logo/pmd-logo-white-600px-squared.png
  docs/images/logo/pmd-old-logo-white-600x440px.png
  docs/images/logo/pmd-old.svg
  docs/pages/pmd/projectdocs/logo.md
Labels: in:documentation

#4464 [core] Fix FileCollector#addSourceFile parameter order
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/lang/document/FileCollector.java
  pmd-core/src/test/java/net/sourceforge/pmd/PmdAnalysisTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/processor/GlobalListenerTest.java
  pmd-core/src/test/java/net/sourceforge/pmd/processor/PmdRunnableTest.java
  pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/BaseParsingHelper.kt
Labels: a:bug

#4473 [doc] Update ANTLR documentation
  docs/_data/sidebars/pmd_sidebar.yml
  docs/pages/pmd/devdocs/major_contributions/adding_a_new_antlr_based_language.md
  docs/pages/pmd/devdocs/major_contributions/adding_a_new_javacc_based_language.md
  docs/pages/pmd/devdocs/major_contributions/adding_new_cpd_language.md
  docs/pages/release_notes.md
  docs/pages/release_notes_pmd7.md
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/impl/AntlrTokenizer.java
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/impl/JavaCCTokenizer.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/antlr4/AntlrGeneratedParserBase.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/javacc/JavaccTokenDocument.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/AbstractVisitorRule.java
  pmd-cpp/src/main/java/net/sourceforge/pmd/cpd/CPPTokenizer.java
  pmd-cs/src/main/java/net/sourceforge/pmd/cpd/CsTokenizer.java
  pmd-dart/src/main/java/net/sourceforge/pmd/cpd/DartTokenizer.java
  pmd-gherkin/src/main/java/net/sourceforge/pmd/lang/gherkin/cpd/GherkinTokenizer.java
  pmd-go/src/main/java/net/sourceforge/pmd/cpd/GoTokenizer.java
  pmd-java/src/main/java/net/sourceforge/pmd/cpd/JavaTokenizer.java
  pmd-javascript/src/main/java/net/sourceforge/pmd/cpd/EcmascriptTokenizer.java
  pmd-jsp/src/main/java/net/sourceforge/pmd/cpd/JSPTokenizer.java
  pmd-kotlin/src/main/antlr4/net/sourceforge/pmd/lang/kotlin/ast/Kotlin.g4
  pmd-kotlin/src/main/antlr4/net/sourceforge/pmd/lang/kotlin/ast/README.md
  pmd-kotlin/src/main/java/net/sourceforge/pmd/cpd/KotlinTokenizer.java
  pmd-kotlin/src/main/java/net/sourceforge/pmd/lang/kotlin/AbstractKotlinRule.java
  pmd-kotlin/src/main/java/net/sourceforge/pmd/lang/kotlin/ast/KotlinInnerNode.java
  pmd-lua/src/main/java/net/sourceforge/pmd/cpd/LuaTokenizer.java
  pmd-matlab/src/main/java/net/sourceforge/pmd/cpd/MatlabTokenizer.java
  pmd-modelica/src/main/java/net/sourceforge/pmd/cpd/ModelicaTokenizer.java
  pmd-objectivec/src/main/java/net/sourceforge/pmd/cpd/ObjectiveCTokenizer.java
  pmd-plsql/src/main/java/net/sourceforge/pmd/cpd/PLSQLTokenizer.java
  pmd-python/src/main/java/net/sourceforge/pmd/cpd/PythonTokenizer.java
  pmd-swift/src/main/antlr4/net/sourceforge/pmd/lang/swift/ast/Swift.g4
  pmd-swift/src/main/java/net/sourceforge/pmd/cpd/SwiftTokenizer.java
  pmd-swift/src/main/java/net/sourceforge/pmd/lang/swift/AbstractSwiftRule.java
  pmd-swift/src/main/java/net/sourceforge/pmd/lang/swift/ast/SwiftInnerNode.java
  pmd-swift/src/main/java/net/sourceforge/pmd/lang/swift/rule/bestpractices/UnavailableFunctionRule.java
  pmd-tsql/src/main/java/net/sourceforge/pmd/lang/tsql/cpd/TSqlTokenizer.java
  pmd-visualforce/src/main/java/net/sourceforge/pmd/cpd/VfTokenizer.java
  pmd-xml/src/main/java/net/sourceforge/pmd/xml/cpd/XmlTokenizer.java
Labels: in:documentation

#4490 [java] ImmutableField - remove @Getter
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ImmutableFieldRule.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/ImmutableField.xml
Labels: a:false-negative

#4491 [dist] Fix pmd.bat script
  docs/pages/release_notes.md
  pmd-dist/src/main/resources/scripts/pmd
  pmd-dist/src/main/resources/scripts/pmd.bat
  pmd-dist/src/test/resources/scripts/pmdtest.bat
Labels: in:cli

#4489 [java] ImmutableField: Remove deprecated property "ignoredAnnotations"
  docs/pages/release_notes.md
  docs/pages/release_notes_pmd7.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/ImmutableFieldRule.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/design/xml/ImmutableField.xml
Labels: is:feature-removal

#4520 [doc] Fix typo: missing closing quotation mark after CPD-END
  docs/pages/pmd/userdocs/cpd/cpd.md
Labels: in:documentation

#4519 [doc] Update doc page, fix fontawesome missing icons
  Gemfile.lock
  docs/Gemfile.lock
  docs/_includes/head.html
  docs/assets/README.md
  docs/assets/fontawesome-free-5.14.0-web/css/all.min.css
  docs/assets/fontawesome-free-5.14.0-web/webfonts/fa-brands-400.eot
  docs/assets/fontawesome-free-5.14.0-web/webfonts/fa-brands-400.ttf
  docs/assets/fontawesome-free-5.14.0-web/webfonts/fa-brands-400.woff
  docs/assets/fontawesome-free-5.14.0-web/webfonts/fa-brands-400.woff2
  docs/assets/fontawesome-free-5.14.0-web/webfonts/fa-regular-400.eot
  docs/assets/fontawesome-free-5.14.0-web/webfonts/fa-regular-400.ttf
  docs/assets/fontawesome-free-5.14.0-web/webfonts/fa-regular-400.woff
  docs/assets/fontawesome-free-5.14.0-web/webfonts/fa-regular-400.woff2
  docs/assets/fontawesome-free-5.14.0-web/webfonts/fa-solid-900.eot
  docs/assets/fontawesome-free-5.14.0-web/webfonts/fa-solid-900.ttf
  docs/assets/fontawesome-free-5.14.0-web/webfonts/fa-solid-900.woff
  docs/assets/fontawesome-free-5.14.0-web/webfonts/fa-solid-900.woff2
  docs/assets/fontawesome-free-5.15.4-web/LICENSE.txt
  docs/assets/fontawesome-free-5.15.4-web/css/all.min.css
  docs/assets/fontawesome-free-5.15.4-web/webfonts/fa-brands-400.eot
  docs/assets/fontawesome-free-5.15.4-web/webfonts/fa-brands-400.svg
  docs/assets/fontawesome-free-5.15.4-web/webfonts/fa-brands-400.ttf
  docs/assets/fontawesome-free-5.15.4-web/webfonts/fa-brands-400.woff
  docs/assets/fontawesome-free-5.15.4-web/webfonts/fa-brands-400.woff2
  docs/assets/fontawesome-free-5.15.4-web/webfonts/fa-regular-400.eot
  docs/assets/fontawesome-free-5.15.4-web/webfonts/fa-regular-400.svg
  docs/assets/fontawesome-free-5.15.4-web/webfonts/fa-regular-400.ttf
  docs/assets/fontawesome-free-5.15.4-web/webfonts/fa-regular-400.woff
  docs/assets/fontawesome-free-5.15.4-web/webfonts/fa-regular-400.woff2
  docs/assets/fontawesome-free-5.15.4-web/webfonts/fa-solid-900.eot
  docs/assets/fontawesome-free-5.15.4-web/webfonts/fa-solid-900.svg
  docs/assets/fontawesome-free-5.15.4-web/webfonts/fa-solid-900.ttf
  docs/assets/fontawesome-free-5.15.4-web/webfonts/fa-solid-900.woff
  docs/assets/fontawesome-free-5.15.4-web/webfonts/fa-solid-900.woff2
  docs/css/customstyles.css
Labels: in:documentation

#4445 [ci] Improve release scripts
  .ci/build.sh
  do-release.sh
Labels: in:pmd-internals
