Repository pmd/pmd, pull requests merged in 2024-08, with the labels that each got.

#5169 [java] Revamp GuardLogStatementRule to allow var, field and array accesses
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ConstantFolder.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/GuardLogStatementRule.java
  pmd-java/src/main/resources/category/java/bestpractices.xml
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/GuardLogStatementTest.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/GuardLogStatement.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/InefficientStringBuffering.xml
Labels: a:false-positive

#5126 [javascript] New rule AvoidConsoleStatements
  .all-contributorsrc
  docs/pages/pmd/projectdocs/credits.md
  docs/pages/release_notes.md
  pmd-javascript/src/main/resources/category/ecmascript/categories.properties
  pmd-javascript/src/main/resources/category/ecmascript/performance.xml
  pmd-javascript/src/test/java/net/sourceforge/pmd/lang/ecmascript/rule/performance/AvoidConsoleStatementsTest.java
  pmd-javascript/src/test/resources/net/sourceforge/pmd/lang/ecmascript/rule/performance/xml/AvoidConsoleStatements.xml
Labels: a:new-rule

#5185 Bump checkstyle from 10.14.0 to 10.18.1
  pom.xml
Labels: dependencies
