Repository pmd/pmd, pull requests merged in 2024-11, with the labels that each got.

#5312 Bump maven-pmd-plugin from 3.24.0 to 3.26.0
  pom.xml
Labels: dependencies, java

#5309 [java] Fix #5293: Parse number of type parameters eagerly
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStub.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/GenericSigBase.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/GenericTypeParameterCounter.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ModuleStub.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ParseLock.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/DeadlockTest.java
  pmd-java/src/test/resources/simplelogger.properties
Labels: in:pmd-internals, in:type-resolution

#5330 [java] Propagate unknown type better when mref is unresolved
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/ExprCheckHelper.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/ExprOps.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/types/TypesTreeDumpTest.java
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/AstTestUtil.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/UnresolvedTypesRecoveryTest.kt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/types/dumptests/UnresolvedThings.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/types/dumptests/UnresolvedThings.txt
Labels: in:type-resolution

#5341 [java] Fix #5083 - UnusedPrivateMethod false positive with mref without target type but with exact method
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/Infer.java
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/MethodRefInferenceTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/UnresolvedTypesRecoveryTest.kt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml
Labels: in:type-resolution

#5289 [java] TooFewBranchesForSwitch - allow list of case constants
  docs/pages/release_notes.md
  pmd-java/src/main/resources/category/java/performance.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/TooFewBranchesForSwitch.xml
Labels: a:false-positive

#5347 [tsql] Flag generated lexer as generated
  pmd-tsql/pom.xml
Labels: in:pmd-internals

#5345 [coco] Remove generated coco files form coverage
  docs/pages/release_notes.md
  pmd-coco/pom.xml
  pmd-coco/src/main/java/net/sourceforge/pmd/lang/coco/ast/CocoBaseListener.java
  pmd-coco/src/main/java/net/sourceforge/pmd/lang/coco/ast/CocoBaseVisitor.java
  pmd-coco/src/main/java/net/sourceforge/pmd/lang/coco/ast/CocoListener.java
  pmd-coco/src/main/java/net/sourceforge/pmd/lang/coco/ast/CocoParser.java
  pmd-coco/src/main/java/net/sourceforge/pmd/lang/coco/ast/CocoVisitor.java
Labels: in:pmd-internals

#5346 [typescript] Add cleanup after generating ts lexer
  antlr4-wrapper.xml
  javacc-wrapper.xml
  pmd-javascript/pom.xml
Labels: in:pmd-internals

#5354 [apex] Updated the docs for UnusedMethod as per discussion #5200
  pmd-apex/src/main/resources/category/apex/design.xml
Labels: in:documentation

#5352 [java] Add permitted subtypes to symbol API
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAnonymousClassDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTClassDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTTypeDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JModifier.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JClassSymbol.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStub.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStubBuilder.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/ast/AstClassSym.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/internal/SymImplementation.java
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/JClassSymbolTest.java
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/asm/AsmLoaderTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/table/internal/LocalTypeScopesTest.kt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/symbols/testdata/sealed/A.class
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/symbols/testdata/sealed/B.class
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/symbols/testdata/sealed/C.class
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/symbols/testdata/sealed/Foo$Bar.class
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/symbols/testdata/sealed/Foo.class
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/symbols/testdata/sealed/FooEnum$1.class
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/symbols/testdata/sealed/FooEnum.class
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/symbols/testdata/sealed/FooRecord.class
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/symbols/testdata/sealed/ImplicitPermitsClause.class
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/symbols/testdata/sealed/ImplicitPermitsClause.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/symbols/testdata/sealed/ImplicitPermitsClauseItf.class
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/symbols/testdata/sealed/Qux$1.class
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/symbols/testdata/sealed/Qux.class
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/symbols/testdata/sealed/SealedTypesTestData.class
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/symbols/testdata/sealed/SealedTypesTestData.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/symbols/testdata/sealed/SubItf.class
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/symbols/testdata/sealed/SubItf2.class
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/symbols/testdata/sealed/X.class
  pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/test/ast/BaseParsingHelper.kt
Labels: in:symbol-table

#5356 Bump build-tools to 28
  .github/workflows/build.yml
  .github/workflows/git-repo-sync.yml
  .github/workflows/troubleshooting.yml
  pom.xml
Labels: dependencies

#5240 Release notes improvements
  .ci/tools/release-notes-add-pr.sh
  .ci/tools/release-notes-generate.sh
  do-release.sh
  docs/pages/pmd/projectdocs/committers/merging_pull_requests.md
  docs/pages/pmd/projectdocs/committers/releasing.md
  docs/pages/release_notes.md
Labels: in:pmd-internals

#5370 [java] Fix #5214 - LambdaCanBeMethodReference issue with method of enclosing class
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/LambdaCanBeMethodReferenceRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypeOps.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/LambdaCanBeMethodReference.xml
Labels: a:bug

#5371 [doc] Improve docs on adding Antlr languages
  docs/pages/pmd/devdocs/major_contributions/adding_a_new_antlr_based_language.md
  docs/pages/pmd/devdocs/major_contributions/adding_new_cpd_language.md
Labels: in:documentation

#5337 [doc] Introducing PMD Guru on Gurubase.io
  README.md
Labels: in:documentation

#5375 Bump pmd from 7.7.0 to 7.8.0
  pom.xml
Labels: dependencies
