Repository pmd/pmd, pull requests merged in 2024-04, with the labels that each got.

#4923 Fix checkstyle config and checkstyle issues
  pmd-ant/src/test/java/net/sourceforge/pmd/ant/CPDTaskTest.java
  pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/QuickstartRulesetTest.java
  pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/cpd/ApexCpdLexerTest.java
  pmd-coco/src/test/java/net/sourceforge/pmd/lang/coco/cpd/CocoCpdLexerTest.java
  pmd-cpp/src/test/java/net/sourceforge/pmd/lang/cpp/cpd/CppCpdLexerTest.java
  pmd-cs/src/test/java/net/sourceforge/pmd/lang/cs/cpd/CsCpdLexerTest.java
  pmd-html/src/test/java/net/sourceforge/pmd/lang/html/ast/HtmlParsingHelper.java
  pmd-html/src/test/java/net/sourceforge/pmd/lang/html/cpd/HtmlCpdLexerTest.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitTestContainsTooManyAssertsRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnitTestsShouldIncludeAssertRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/design/LawOfDemeterRule.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/JavaAttributesPrinter.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/JavaParsingHelper.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/LanguageVersionTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/QuickstartRulesetTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/JDKVersionTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/Java14TreeDumpTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/Java15TreeDumpTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/Java16TreeDumpTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/Java17TreeDumpTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/Java9TreeDumpTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/ast/ParserCornersTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/cpd/JavaCpdLexerTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnit4TestShouldUseAfterAnnotationTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/bestpractices/JUnit4TestShouldUseBeforeAnnotationTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/internal/TestFrameworksUtilTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/types/TypesTreeDumpTest.java
  pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/EcmascriptParser.java
  pmd-javascript/src/test/java/net/sourceforge/pmd/lang/ecmascript/ast/JsParsingHelper.java
  pmd-javascript/src/test/java/net/sourceforge/pmd/lang/ecmascript/cpd/AnyCpdLexerForTypescriptTest.java
  pmd-javascript/src/test/java/net/sourceforge/pmd/lang/ecmascript/cpd/EcmascriptCpdLexerTest.java
  pmd-jsp/src/test/java/net/sourceforge/pmd/lang/jsp/ast/JspParsingHelper.java
  pmd-jsp/src/test/java/net/sourceforge/pmd/lang/jsp/cpd/JspCpdLexerTest.java
  pmd-julia/src/test/java/net/sourceforge/pmd/lang/julia/cpd/JuliaCpdLexerTest.java
  pmd-kotlin/src/main/java/net/sourceforge/pmd/lang/kotlin/ast/KotlinNameDictionary.java
  pmd-kotlin/src/test/java/net/sourceforge/pmd/lang/kotlin/ast/KotlinParsingHelper.java
  pmd-modelica/src/test/java/net/sourceforge/pmd/lang/modelica/ModelicaParsingHelper.java
  pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/PlsqlParsingHelper.java
  pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/ExecuteImmediateBulkCollectTest.java
  pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/ParenthesisGroupTest.java
  pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/ast/PlsqlTreeDumpTest.java
  pmd-plsql/src/test/java/net/sourceforge/pmd/lang/plsql/cpd/PLSQLCpdLexerTest.java
  pmd-scala-modules/pmd-scala-common/src/main/java/net/sourceforge/pmd/lang/scala/ScalaLanguageModule.java
  pmd-scala-modules/pmd-scala-common/src/test/java/net/sourceforge/pmd/lang/scala/ast/ScalaParsingHelper.java
  pmd-swift/src/test/java/net/sourceforge/pmd/lang/swift/ast/SwiftParsingHelper.java
  pmd-swift/src/test/java/net/sourceforge/pmd/lang/swift/cpd/SwiftCpdLexerTest.java
  pmd-velocity/pmd-velocity-checkstyle-suppressions.xml
  pmd-visualforce/src/test/java/net/sourceforge/pmd/lang/visualforce/LanguageVersionTest.java
  pmd-xml/src/test/java/net/sourceforge/pmd/lang/xml/LanguageVersionTest.java
  pom.xml
Labels: in:pmd-internals

#4906 [java] CloseResource should treat parameters as external even if casted when assigned to a local variable
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/errorprone/CloseResourceRule.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloseResource.xml
Labels: a:false-positive

#4925 [java] Support explicitly typed lambdas
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/JClassType.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/ExprCheckHelper.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/Infer.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/InferenceContext.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/package-info.java
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/ExplicitTypesTest.kt
Labels: an:enhancement, in:type-resolution

#4936 [apex] Add ASTAnnotation#getRawName
  docs/pages/release_notes.md
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ASTAnnotation.java
  pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/ast/ASTAnnotationTest.java
Labels: an:enhancement

#4949 [core] Disable Caching in URLConnection for ClasspathClassLoader
  .all-contributorsrc
  docs/pages/pmd/projectdocs/credits.md
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/internal/util/ClasspathClassLoader.java
  pmd-core/src/test/java/net/sourceforge/pmd/internal/util/ClasspathClassLoaderTest.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStub.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/Loader.java
Labels: a:bug

#4951 [compat6] Make compat6 forward compatible with maven-pmd-plugin 3.22.0
  pmd-compat6/src/main/java/net/sourceforge/pmd/PMDConfiguration.java
  pmd-compat6/src/main/java/net/sourceforge/pmd/Report.java
  pmd-compat6/src/main/java/net/sourceforge/pmd/reporting/Report.java
Labels: in:pmd-internals

#4956 [core] Add a filter possibility to FileCollector
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/internal/util/FileCollectionUtil.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/document/FileCollector.java
  pmd-core/src/test/java/net/sourceforge/pmd/cpd/CpdAnalysisTest.java
Labels: a:bug

#4970 [doc] Add small logo variant
  docs/images/logo/PMD_small.svg
  docs/images/logo/favicon.ico
  docs/images/logo/pmd-logo-small-300px.png
  docs/images/logo/pmd-logo-small-64px.png
  docs/images/logo/pmd-logo-small-white-300px.png
  docs/images/logo/pmd-logo-small-white-64px.png
  docs/pages/pmd/projectdocs/logo.md
Labels: in:documentation

#4918 [java] New rule LambdaCanBeMethodReference
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTLambdaExpression.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/internal/PrettyPrintingUtil.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/codestyle/LambdaCanBeMethodReferenceRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/internal/infer/ast/LambdaMirrorImpl.java
  pmd-java/src/main/resources/category/java/codestyle.xml
  pmd-java/src/main/resources/rulesets/java/quickstart.xml
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/rule/codestyle/LambdaCanBeMethodReferenceTest.java
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/TestExtensions.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/TypeInferenceTest.kt
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/LambdaCanBeMethodReference.xml
Labels: a:new-rule

#4966 [core] Make CPD report maximal, non-repeating and non-overlapping duplicates
  docs/pages/release_notes.md
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/MatchCollector.java
  pmd-core/src/test/java/net/sourceforge/pmd/cpd/MatchAlgorithmTest.java
  pmd-cpp/src/test/java/net/sourceforge/pmd/lang/cpp/cpd/CppCpdTest.java
  pmd-cpp/src/test/resources/net/sourceforge/pmd/lang/cpp/cpd/testdata/ctype.c
Labels: an:enhancement, in:cpd

#4979 [java] Properly handle @MethodSource in UnusedPrivateMethod
  docs/pages/release_notes.md
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/bestpractices/UnusedPrivateMethodRule.java
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/UnusedPrivateMethod.xml
Labels: a:false-positive

#4968 [core] Typesafe saxon node iterators
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/internal/BaseNodeInfo.java
Labels: in:pmd-internals, in:xpath

#4976 Fix release scripts
  .github/workflows/build.yml
  do-release.sh
  docs/pages/pmd/projectdocs/committers/releasing.md
  pmd-java/src/main/resources/rulesets/java/quickstart.xml
Labels: in:pmd-internals
