Repository pmd/pmd, pull requests merged in 2024-03, with the labels that each got.

#4849 [core] Fix NPE in AbstractAnalysisCache in case of processing errors
  pmd-core/src/main/java/net/sourceforge/pmd/cache/internal/AbstractAnalysisCache.java
  pmd-core/src/test/java/net/sourceforge/pmd/cache/internal/FileAnalysisCacheTest.java
Labels: a:bug

#4850 Fix kotlin compiler warnings
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexTreeBuilder.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTCastExpressionTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTFieldAccessTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTMethodCallTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTMethodDeclarationTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTPatternTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTSuperExpressionTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTThisExpressionTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTTypeTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ASTUnaryExpressionTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/Java11Test.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/KotlinTestingDsl.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/NodeParsingCtx.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/ParenthesesTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/TestExtensions.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/TypeDisambiguationTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/UsageResolutionTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/ast/VarDisambiguationTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/AstSymbolTests.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/PrimitiveSymbolTests.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/ReflectedClassSymbolTests.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/ReflectedFieldSymbolTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/Utils.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/asm/BrokenClasspathTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/asm/SigParserTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/table/internal/HeaderScopesTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/table/internal/LocalTypeScopesTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/table/internal/MemberInheritanceTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/table/internal/VarScopingTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/ArraySymbolTests.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/BoxingTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/CaptureTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/SubtypingTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/TestUtilitiesForTypes.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/TypeCreationDsl.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/TypeEqualityTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/TypeGenerationUtil.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/TypesFromReflectionTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/ast/ConversionContextTests.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/BranchingExprsTestCases.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/CaptureInferenceTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/CtorInferenceTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/Java7InferenceTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/OverridingTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/SpecialMethodsTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/StandaloneTypesTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/StressTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/TypeAnnotationsInferenceTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/TypeInferenceTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/internal/infer/UnresolvedTypesRecoveryTest.kt
  pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/cpd/test/CpdTextComparisonTest.kt
  pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/NodeExtensions.kt
  pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/NodePrinters.kt
  pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/lang/ast/test/TestUtils.kt
  pmd-lang-test/src/main/kotlin/net/sourceforge/pmd/test/BaseTextComparisonTest.kt
Labels: in:pmd-internals

#4851 [core] NodeStreamBlanketTest - prefilter the test data
  pmd-core/src/test/java/net/sourceforge/pmd/lang/ast/internal/NodeStreamBlanketTest.java
Labels: in:pmd-internals

#4854 Update various dependencies
  .mvn/wrapper/maven-wrapper.properties
  pmd-apex/pom.xml
  pmd-core/pom.xml
  pmd-dist/pom.xml
  pmd-html/pom.xml
  pmd-java/pom.xml
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/internal/TestFrameworksUtil.java
  pmd-scala-modules/pmd-scala-common/pom.xml
  pmd-scala-modules/pmd-scala-common/src/test/resources/net/sourceforge/pmd/lang/scala/ast/testdata/List.txt
  pmd-scala-modules/pmd-scala_2.12/pom.xml
  pmd-scala-modules/pmd-scala_2.13/pom.xml
  pmd-test-schema/pom.xml
  pom.xml
Labels: dependencies

#4855 Fix javadoc syntax errors (doclint)
  antlr4-wrapper.xml
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/metrics/ApexMetrics.java
  pmd-compat6/src/main/java/net/sourceforge/pmd/PMDConfiguration.java
  pmd-compat6/src/main/java/net/sourceforge/pmd/PmdAnalysis.java
  pmd-compat6/src/main/java/net/sourceforge/pmd/Report.java
  pmd-compat6/src/main/java/net/sourceforge/pmd/cpd/CSVRenderer.java
  pmd-compat6/src/main/java/net/sourceforge/pmd/cpd/renderer/CPDRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/PMDConfiguration.java
  pmd-core/src/main/java/net/sourceforge/pmd/PmdAnalysis.java
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/CSVRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/CpdAnalysis.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/NodeStream.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/AbstractNode.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/ast/impl/javacc/JavaccTokenDocument.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/document/TextDocument.java
  pmd-core/src/main/java/net/sourceforge/pmd/properties/PropertyBuilder.java
  pmd-core/src/main/java/net/sourceforge/pmd/properties/PropertyFactory.java
  pmd-core/src/main/java/net/sourceforge/pmd/reporting/FileAnalysisListener.java
  pmd-core/src/main/java/net/sourceforge/pmd/reporting/Report.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/AssertionUtil.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/IteratorUtil.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTAmbiguousName.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTInfixExpression.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTInitializer.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTLambdaExpression.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTLocalVariableDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTModuleDeclaration.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTRecordComponent.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTUnnamedPattern.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/JavaVisitorBase.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/metrics/JavaMetrics.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/rule/performance/InefficientEmptyStringCheckRule.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JTypeDeclSymbol.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/InvocationMatcher.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/JClassType.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/JTypeMirror.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/types/TypesFromReflection.java
  pmd-modelica/src/main/java/net/sourceforge/pmd/lang/modelica/resolver/ResolutionResult.java
  pmd-plsql/etc/grammar/PLSQL.jjt
  pmd-test/src/main/java/net/sourceforge/pmd/test/AbstractAntTestHelper.java
  pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/rule/DomXPathRule.java
  pom.xml
Labels: in:documentation

#4859 [doc] Doc release notes 7
  Gemfile
  Gemfile.lock
  do-release.sh
  docs/Gemfile
  docs/Gemfile.lock
  docs/_includes/language_info.html
  docs/_plugins/javadoc_tag.rb
  docs/_plugins/jdoc_namespace_tag.rb
  docs/_plugins/tocmaker_block.rb
  docs/css/customstyles.css
  docs/pages/pmd/about/help.md
  docs/pages/pmd/devdocs/development.md
  docs/pages/pmd/devdocs/major_contributions/adding_a_new_antlr_based_language.md
  docs/pages/pmd/devdocs/major_contributions/adding_a_new_javacc_based_language.md
  docs/pages/pmd/devdocs/major_contributions/adding_new_cpd_language.md
  docs/pages/pmd/languages/java.md
  docs/pages/pmd/languages/kotlin.md
  docs/pages/pmd/languages/language_properties.md
  docs/pages/pmd/languages/modelica.md
  docs/pages/pmd/languages/velocity.md
  docs/pages/pmd/languages/xml.md
  docs/pages/pmd/projectdocs/trivia/news.md
  docs/pages/pmd/userdocs/cli_reference.md
  docs/pages/pmd/userdocs/cpd/cpd.md
  docs/pages/pmd/userdocs/extending/writing_xpath_rules.md
  docs/pages/pmd/userdocs/incremental_analysis.md
  docs/pages/pmd/userdocs/installation.md
  docs/pages/pmd/userdocs/migrating_to_pmd7.md
  docs/pages/pmd/userdocs/tools/gradle.md
  docs/pages/release_notes.md
  docs/pages/release_notes_pmd7.md
  docs/render_release_notes.rb
  pmd-core/src/main/java/net/sourceforge/pmd/lang/metrics/MetricsUtil.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/InternalApiBridge.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/xpath/XPathRule.java
  pmd-core/src/main/java/net/sourceforge/pmd/util/internal/ResourceLoader.java
  pmd-doc/src/main/java/net/sourceforge/pmd/doc/internal/DeadLinksChecker.java
  pmd-java/src/main/resources/category/java/errorprone.xml
  pmd-java/src/main/resources/category/java/performance.xml
Labels: in:documentation

#4894 Fix #4791 Error caused by space in JDK path
  pmd-dist/src/main/resources/scripts/pmd.bat
Labels: in:cli
