Repository pmd/pmd, pull requests merged in 2024-07, with the labels that each got.

#5107 [doc] Update maven.md - Typo fixed for maven target
  docs/pages/pmd/userdocs/tools/maven.md
Labels: in:documentation

#5102 [core] Don't log warning about skipLexicalErrors twice
  docs/pages/release_notes.md
  pmd-ant/src/main/java/net/sourceforge/pmd/ant/CPDTask.java
  pmd-cli/src/main/java/net/sourceforge/pmd/cli/commands/internal/CpdCommand.java
  pmd-cli/src/test/java/net/sourceforge/pmd/cli/BaseCliTest.java
  pmd-cli/src/test/java/net/sourceforge/pmd/cli/CpdCliTest.java
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/CPDConfiguration.java
  pmd-core/src/main/java/net/sourceforge/pmd/cpd/CpdAnalysis.java
  pmd-core/src/test/java/net/sourceforge/pmd/cpd/CpdAnalysisTest.java
Labels: in:cpd

#5136 Deprecate generated parser implementations
  docs/pages/release_notes.md
  pmd-jsp/etc/grammar/Jsp.jjt
  pmd-plsql/etc/grammar/PLSQL.jjt
  pmd-velocity/etc/grammar/Vtl.jjt
  pmd-visualforce/etc/grammar/Vf.jjt
Labels: is:deprecation

#5100 Enable Dependabot
  .github/dependabot.yml
  do-release.sh
  docs/pages/pmd/projectdocs/committers/releasing.md
Labels: dependencies
