Repository pmd/pmd, pull requests merged in 2025-03, with the labels that each got.

#5558 Bump PMD from 7.10.0 to 7.11.0
  pom.xml
Labels: dependencies

#5571 Bump nokogiri from 1.16.7 to 1.18.3
  Gemfile.lock
  docs/Gemfile.lock
Labels: dependencies

#5572 Bump uri from 0.13.1 to 1.0.3
  Gemfile.lock
  docs/Gemfile.lock
Labels: dependencies

#5556 [ci] New workflow "Publish Results from Pull Requests"
  .ci/files/Gemfile
  .ci/files/Gemfile.lock
  .ci/files/pmdtester.rb
  .github/dependabot.yml
  .github/workflows/publish-pull-requests.yml
  .github/workflows/pull-requests.yml
  Dangerfile
  Gemfile.lock
  docs/pages/pmd/devdocs/github_actions_workflows.md
Labels: in:pmd-internals

#5583 [java] Fix race condition in ClassStub for inner classes
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStub.java
Labels: a:bug

#5588 [java] Fix crash when parsing class for anonymous class
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/JClassSymbol.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStub.java
  pmd-java/src/main/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStubBuilder.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/internal/asm/ClassStubTest.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/testdata/EnumConstantWithBody.java
  pmd-java/src/test/java/net/sourceforge/pmd/lang/java/symbols/testdata/LocalClasses.java
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/symbols/internal/asm/SigParserTest.kt
  pmd-java/src/test/kotlin/net/sourceforge/pmd/lang/java/types/TypeCreationDsl.kt
Labels: a:bug

#5619 Bump nokogiri from 1.18.3 to 1.18.5
  .ci/files/Gemfile.lock
  docs/Gemfile.lock
Labels: dependencies, ruby

#5618 [doc] Fix search index
  docs/_plugins/custom_filters.rb
  docs/search.json
Labels: a:bug, in:documentation
