Repository pmd/pmd, pull requests merged in 2025-09, with the labels that each got.

#5958 [core] CSVRenderer: Add begin and end for line and columns (default off)
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/CSVRenderer.java
  pmd-core/src/main/java/net/sourceforge/pmd/renderers/ColumnDescriptor.java
  pmd-core/src/test/java/net/sourceforge/pmd/renderers/CSVRendererTest.java
Labels: an:enhancement

#6076 Bump pmdtester from 1.6.0 to 1.6.1
  .ci/files/Gemfile.lock
Labels: dependencies, ruby

#6074 [apex] Fix @SuppressWarnings with whitespace around comma
  .all-contributorsrc
  docs/pages/pmd/projectdocs/credits.md
  docs/pages/release_notes.md
  pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ApexAnnotationSuppressor.java
  pmd-apex/src/test/java/net/sourceforge/pmd/lang/apex/SuppressWarningsTest.java
Labels: a:bug
