Repository pmd/pmd, pull requests merged in 2025-04, with the labels that each got.

#5641 Bump PMD from 7.11.0 to 7.12.0
  pom.xml
Labels: dependencies

#5623 [dist] Make pmd launch script compatible with /bin/sh
  pmd-dist/src/main/resources/scripts/pmd
Labels: an:enhancement

#5671 Bump checkstyle from 10.21.4 to 10.23.0
  .github/workflows/build.yml
  .github/workflows/git-repo-sync.yml
  .github/workflows/troubleshooting.yml
  pom.xml
Labels: dependencies, java

#5672 [doc] Fix its/it's and doable/double typos
  pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/bestpractices/xml/AvoidGlobalModifier.xml
  pmd-core/src/main/java/net/sourceforge/pmd/AbstractConfiguration.java
  pmd-core/src/main/java/net/sourceforge/pmd/benchmark/TimeTracker.java
  pmd-core/src/main/java/net/sourceforge/pmd/cache/internal/RawFileFingerprinter.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/LanguageVersionDiscoverer.java
  pmd-core/src/main/java/net/sourceforge/pmd/lang/rule/RuleSetFactory.java
  pmd-doc/src/test/resources/expected/java.md
  pmd-doc/src/test/resources/expected/sample.md
  pmd-doc/src/test/resources/rulesets/ruledoctest/sample.xml
  pmd-doc/src/test/resources/rulesets/ruledoctest/sample2.xml
  pmd-java/src/main/resources/category/java/multithreading.xml
  pmd-java/src/main/resources/category/java/performance.xml
  pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/ant/classpathtest/ruleset.xml
  pmd-velocity/src/main/javacc/Vtl.jjt
  pmd-visualforce/src/main/java/net/sourceforge/pmd/lang/visualforce/DataType.java
Labels: in:documentation

#5685 [doc] typo fix in PMD Designer reference
  docs/pages/pmd/userdocs/extending/designer_reference.md
Labels: in:documentation

#5704 Bump nokogiri from 1.18.5 to 1.18.8
  .ci/files/Gemfile.lock
  docs/Gemfile.lock
Labels: dependencies, ruby
